In [1]:
import numpy as np
import pandas as pd

In [6]:
# 1
df = pd.read_csv('netflix.csv', parse_dates=['date_added'])

/var/folders/ly/4m8_p07j62l8tfy4gs_lj7100000gn/T/ipykernel_2550/3726533635.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv('netflix.csv', parse_dates=['date_added'])

In [7]:
df

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [10]:
df.count()

title         5837
director      3936
date_added    5195
type          5837
dtype: int64

In [11]:
len(df)

5837

In [12]:
df['type'] = df['type'].astype('category')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [14]:
# 2
df[df['title'] == 'Limitless']

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [16]:
# 3
df[(df['director'] == 'Robert Rodriguez') & (df['type'] == 'Movie')]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [20]:
# 4
df[(df['date_added'] == '2019-07-31') | (df['director'] == 'Robert Altman')].sort_values(by=['director', 'date_added'], na_position='first')

                                title       director date_added     type
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
611                            Popeye  Robert Altman 2019-11-24    Movie

In [21]:
# 5
directors = ['Orson Welles', 'Aditya Kripalani', 'Sam Raimi']

In [23]:
df[df['director'].isin(directors)].sort_values(by=['director'])

                           title          director date_added   type
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie
946                 The Stranger      Orson Welles 2018-07-19  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie

In [25]:
# 6
df[df['date_added'].between(inclusive='left', left='2019-05-01', right='2019-06-01')].sort_values(by=['date_added'])

                                   title          director date_added     type
5829                The Kindness Diaries               NaN 2019-05-01  TV Show
2883               Le serment des Hitler    Emmanuel Amara 2019-05-01    Movie
2407                 Roswell, New Mexico               NaN 2019-05-01  TV Show
2946           Robin Hood: The Rebellion   Nicholas Winter 2019-05-01    Movie
3059  Kill Hitler! The Luck of the Devil  Frédéric Tonolli 2019-05-01    Movie
...                                  ...               ...        ...      ...
3297                          Ragini MMS   Pawan Kripalani 2019-05-31    Movie
2164                          Koi Aap Sa      Partho Mitra 2019-05-31    Movie
2941                          C Kkompany      Sachin Yardi 2019-05-31    Movie
4975                                   P     Paul Spurrier 2019-05-31    Movie
29                            Chopsticks      Sachin Yardi 2019-05-31    Movie

[161 rows x 4 columns]

In [30]:
# 7
df1 = df.dropna(subset=['director'])

In [31]:
len(df1)

3936

In [32]:
df1.count()

title         3936
director      3936
date_added    3901
type          3936
dtype: int64

In [37]:
# 8
df1 = df['date_added'].value_counts().reset_index()

In [42]:
df1[df1['count'] == 1]['date_added'].sort_values()

921    2008-01-01
850    2008-02-04
1032   2009-05-05
1027   2009-11-18
1072   2010-11-01
          ...
937    2019-11-03
1049   2019-11-07
815    2019-11-12
809    2019-11-13
761    2019-11-17
Name: date_added, Length: 391, dtype: datetime64[ns]

In [46]:
df.dropna(subset=['date_added']).drop_duplicates(subset=['date_added'], keep=False)['date_added'].sort_values()

384    2008-01-01
4888   2008-02-04
2743   2009-05-05
2811   2009-11-18
2314   2010-11-01
          ...
145    2019-11-03
1775   2019-11-07
4981   2019-11-12
4008   2019-11-13
3492   2019-11-17
Name: date_added, Length: 391, dtype: datetime64[ns]