In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('happiness.csv')
df

,Country,Score,GDP per capita,Social support,Life expectancy,Generosity
0,Finland,7.769,1.340,1.587,0.986,0.153
1,Denmark,7.600,1.383,1.573,0.996,0.252
2,Norway,7.554,1.488,1.582,1.028,0.271
3,Iceland,7.494,1.380,1.624,1.026,0.354
4,Netherlands,7.488,1.396,1.522,0.999,0.322
...,...,...,...,...,...,...
151,Rwanda,3.334,0.359,0.711,0.614,0.217
152,Tanzania,3.231,0.476,0.885,0.499,0.276
153,Afghanistan,3.203,0.350,0.517,0.361,0.158
154,Central African Republic,3.083,0.026,0.000,0.105,0.235
155,South Sudan,2.853,0.306,0.575,0.295,0.202

In [4]:
df[df['Country'] == 'Russia']

   Country  Score  GDP per capita  Social support  Life expectancy  Generosity
67  Russia  5.648           1.183           1.452            0.726       0.082

In [7]:
df.sort_values(by='Life expectancy', ascending=False).head(50)

,Country,Score,GDP per capita,Social support,Life expectancy,Generosity
33,Singapore,6.262,1.572,1.463,1.141,0.271
75,Hong Kong,5.430,1.438,1.277,1.122,0.258
57,Japan,5.886,1.327,1.419,1.088,0.069
29,Spain,6.354,1.286,1.484,1.062,0.153
5,Switzerland,7.480,1.452,1.526,1.052,0.263
23,France,6.592,1.324,1.472,1.045,0.111
48,Cyprus,6.046,1.263,1.223,1.042,0.190
63,Northern Cyprus,5.718,1.263,1.252,1.042,0.191
35,Italy,6.223,1.294,1.488,1.039,0.158
8,Canada,7.278,1.365,1.505,1.039,0.285
10,Australia,7.228,1.372,1.548,1.036,0.332
53,South Korea,5.895,1.301,1.219,1.036,0.175
12,Israel,7.139,1.276,1.455,1.029,0.261
2,Norway,7.554,1.488,1.582,1.028,0.271
7,New Zealand,7.307,1.303,1.557,1.026,0.330
3,Iceland,7.494,1.380,1.624,1.026,0.354
9,Austria,7.246,1.376,1.475,1.016,0.244
13,Luxembourg,7.090,1.609,1.479,1.012,0.194
6,Sweden,7.343,1.387,1.487,1.009,0.267
81,Greece,5.287,1.181,1.156,0.999,0.000
21,Malta,6.726,1.300,1.520,0.999,0.375
4,Netherlands,7.488,1.396,1.522,0.999,0.322
15,Ireland,7.021,1.499,1.553,0.999,0.298
65,Portugal,5.693,1.221,1.431,0.999,0.047
1,Denmark,7.600,1.383,1.573,0.996,0.252
14,United Kingdom,7.054,1.333,1.538,0.996,0.348
16,Germany,6.985,1.373,1.454,0.987,0.261
0,Finland,7.769,1.340,1.587,0.986,0.153
17,Belgium,6.923,1.356,1.504,0.986,0.160
11,Costa Rica,7.167,1.034,1.441,0.963,0.144
43,Slovenia,6.118,1.258,1.523,0.953,0.144
19,Czech Republic,6.852,1.269,1.487,0.920,0.046
25,Chile,6.444,1.159,1.369,0.920,0.187
74,Croatia,5.432,1.155,1.266,0.914,0.119
24,Taiwan,6.446,1.368,1.430,0.914,0.242
30,Panama,6.321,1.149,1.442,0.910,0.109
92,China,5.191,1.029,1.125,0.893,0.058
32,Uruguay,6.293,1.124,1.465,0.891,0.127
39,Poland,6.182,1.206,1.438,0.884,0.117
46,Argentina,6.086,1.092,1.432,0.881,0.066
37,Slovakia,6.198,1.246,1.504,0.881,0.121
106,Albania,4.719,0.947,0.848,0.874,0.178
18,United States,6.892,1.433,1.457,0.874,0.280
54,Estonia,5.893,1.237,1.528,0.874,0.103
28,Qatar,6.374,1.684,1.313,0.871,0.220
72,Montenegro,5.523,1.051,1.361,0.871,0.142
36,Bahrain,6.199,1.362,1.368,0.871,0.255
49,Ecuador,6.028,0.912,1.312,0.868,0.126
22,Mexico,6.595,1.070,1.323,0.861,0.074
69,Serbia,5.603,1.004,1.383,0.854,0.137

In [12]:
df[df['Country'].isin(['United States', 'Russia'])]

,Country,Score,GDP per capita,Social support,Life expectancy,Generosity
18,United States,6.892,1.433,1.457,0.874,0.280
67,Russia,5.648,1.183,1.452,0.726,0.082

In [21]:
pd.describe_option('display.max_rows')

display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]

In [22]:
pd.describe_option('max_col')

display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]

In [23]:
pd.options.display.max_rows

60

In [24]:
pd.options.display.max_columns

20

In [25]:
pd.describe_option('display.precision')

display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]

In [26]:
pd.options.display.precision = 2

In [28]:
df

,Country,Score,GDP per capita,Social support,Life expectancy,Generosity
0,Finland,7.77,1.34,1.59,0.99,0.15
1,Denmark,7.60,1.38,1.57,1.00,0.25
2,Norway,7.55,1.49,1.58,1.03,0.27
3,Iceland,7.49,1.38,1.62,1.03,0.35
4,Netherlands,7.49,1.40,1.52,1.00,0.32
...,...,...,...,...,...,...
151,Rwanda,3.33,0.36,0.71,0.61,0.22
152,Tanzania,3.23,0.48,0.89,0.50,0.28
153,Afghanistan,3.20,0.35,0.52,0.36,0.16
154,Central African Republic,3.08,0.03,0.00,0.10,0.23
155,South Sudan,2.85,0.31,0.57,0.29,0.20

In [29]:
pd.reset_option('display.precision')

In [30]:
df

,Country,Score,GDP per capita,Social support,Life expectancy,Generosity
0,Finland,7.769,1.340,1.587,0.986,0.153
1,Denmark,7.600,1.383,1.573,0.996,0.252
2,Norway,7.554,1.488,1.582,1.028,0.271
3,Iceland,7.494,1.380,1.624,1.026,0.354
4,Netherlands,7.488,1.396,1.522,0.999,0.322
...,...,...,...,...,...,...
151,Rwanda,3.334,0.359,0.711,0.614,0.217
152,Tanzania,3.231,0.476,0.885,0.499,0.276
153,Afghanistan,3.203,0.350,0.517,0.361,0.158
154,Central African Republic,3.083,0.026,0.000,0.105,0.235
155,South Sudan,2.853,0.306,0.575,0.295,0.202