In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_json('data/cities.json')
df

,city,growth_from_2000_to_2013,latitude,longitude,population,rank,state
0,New York,4.8%,40.712784,-74.005941,8405837,1,New York
1,Los Angeles,4.8%,34.052234,-118.243685,3884307,2,California
2,Chicago,-6.1%,41.878114,-87.629798,2718782,3,Illinois
3,Houston,11.0%,29.760427,-95.369803,2195914,4,Texas
4,Philadelphia,2.6%,39.952584,-75.165222,1553165,5,Pennsylvania
...,...,...,...,...,...,...,...
995,Weslaco,28.8%,26.159519,-97.990837,37093,996,Texas
996,Keizer,14.4%,44.990119,-123.026208,37064,997,Oregon
997,Spanish Fork,78.1%,40.114955,-111.654923,36956,998,Utah
998,Beloit,2.9%,42.508348,-89.031776,36888,999,Wisconsin
999,Panama City,0.1%,30.158813,-85.660206,36877,1000,Florida

In [3]:
df['population'].mean()

np.float64(131132.443)

In [4]:
df['population'].median()

68207.0

In [5]:
df['population'].is_monotonic_decreasing

True

In [18]:
df.iloc[50:]['population'].mean()

np.float64(87027.38736842106)

In [19]:
df.iloc[50:]['population'].median()

65796.0

In [9]:
df.head()

,city,growth_from_2000_to_2013,latitude,longitude,population,rank,state
0,New York,4.8%,40.712784,-74.005941,8405837,1,New York
1,Los Angeles,4.8%,34.052234,-118.243685,3884307,2,California
2,Chicago,-6.1%,41.878114,-87.629798,2718782,3,Illinois
3,Houston,11.0%,29.760427,-95.369803,2195914,4,Texas
4,Philadelphia,2.6%,39.952584,-75.165222,1553165,5,Pennsylvania

In [14]:
df.nlargest(1, columns=['latitude'], keep='all')

,city,growth_from_2000_to_2013,latitude,longitude,population,rank,state
62,Anchorage,15.4%,61.218056,-149.900278,300950,63,Alaska

In [17]:
df['state'].value_counts()

state
California              212
Texas                    83
Florida                  73
Illinois                 52
Massachusetts            36
Ohio                     33
Michigan                 31
Washington               28
Arizona                  25
Minnesota                24
North Carolina           22
New Jersey               22
Indiana                  21
Colorado                 21
Wisconsin                20
Utah                     19
Georgia                  18
Virginia                 17
New York                 17
Tennessee                17
Missouri                 16
Connecticut              15
Oregon                   14
Pennsylvania             13
Iowa                     13
South Carolina           12
Alabama                  12
Kansas                   11
Oklahoma                 11
Arkansas                 10
Louisiana                 9
Idaho                     8
Maryland                  7
New Mexico                7
Mississippi               6
Rhode Island              6
Nevada                    6
Kentucky                  5
Nebraska                  4
North Dakota              4
Montana                   4
New Hampshire             3
South Dakota              2
Delaware                  2
Wyoming                   2
West Virginia             2
Alaska                    1
Hawaii                    1
District of Columbia      1
Maine                     1
Vermont                   1
Name: count, dtype: int64

In [20]:
# 20.1

In [32]:
df.loc[df['growth_from_2000_to_2013'] == '', 'growth_from_2000_to_2013'] = '0.0%'

In [36]:
df['growth_from_2000_to_2013'] = df['growth_from_2000_to_2013'].str.replace('%', '').astype(np.float32) / 100

In [37]:
df['growth_from_2000_to_2013'].describe()[['mean', '50%']]

mean    0.22936
50%     0.09650
Name: growth_from_2000_to_2013, dtype: float64

In [39]:
df['category'] = pd.cut(df['growth_from_2000_to_2013'], bins=[df['growth_from_2000_to_2013'].min(), 0, df['growth_from_2000_to_2013'].max()], labels=['neg', 'pos'], include_lowest=True)

In [40]:
df['category'].value_counts()

category
pos    847
neg    153
Name: count, dtype: int64

In [41]:
# 20.3

In [42]:
df.loc[(df['longitude'] > df['longitude'].mean() + 2 * df['longitude'].std()) | (df['longitude'] < df['longitude'].mean() - 2 * df['longitude'].std()), 'city']

53     Honolulu
62    Anchorage
Name: city, dtype: object

In [43]:
df.loc[(df['latitude'] > df['latitude'].mean() + 2 * df['latitude'].std()) | (df['latitude'] < df['latitude'].mean() - 2 * df['latitude'].std()), 'city']

43                 Miami
53              Honolulu
62             Anchorage
88               Hialeah
130          Brownsville
138      Fort Lauderdale
145           Cape Coral
149       Pembroke Pines
173            Hollywood
187              McAllen
195              Miramar
207        Coral Springs
242        Miami Gardens
268              Everett
275        Pompano Beach
279      West Palm Beach
306                Davie
335          Miami Beach
339           Plantation
341              Sunrise
344           Boca Raton
389           Bellingham
400              Mission
403             Edinburg
421      Deerfield Beach
454                Pharr
473        Boynton Beach
487           Lauderhill
496               Weston
500           Fort Myers
526            Harlingen
541            Homestead
543         Delray Beach
551           Marysville
552              Tamarac
579          North Miami
587           Wellington
635        Coconut Creek
655              Margate
664          Grand Forks
737                Doral
751         Coral Gables
786       Bonita Springs
802                Minot
847           Cutler Bay
848         Oakland Park
849    North Miami Beach
863     North Lauderdale
954           Greenacres
956     Hallandale Beach
990             Aventura
995              Weslaco
Name: city, dtype: object