In [7]:
import numpy as np
import pandas as pd
import string

In [3]:
df = pd.read_csv(
    'data/winemag-150k-reviews.csv',
    usecols=['country', 'province', 'description', 'variety']
)

df

,country,description,province,variety
0,US,This tremendous 100% varietal wine hails from ...,California,Cabernet Sauvignon
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Northern Spain,Tinta de Toro
2,US,Mac Watson honors the memory of a wine once ma...,California,Sauvignon Blanc
3,US,"This spent 20 months in 30% new French oak, an...",Oregon,Pinot Noir
4,France,"This is the top wine from La Bégude, named aft...",Provence,Provence red blend
...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,Southern Italy,White Blend
150926,France,"Offers an intriguing nose with ginger, lime an...",Champagne,Champagne Blend
150927,Italy,This classic example comes from a cru vineyard...,Southern Italy,White Blend
150928,France,"A perfect salmon shade, with scents of peaches...",Champagne,Champagne Blend
150929,Italy,More Pinot Grigios should taste like this. A r...,Northeastern Italy,Pinot Grigio

In [12]:
words = df['description'].str.split().explode().str.strip().str.strip(string.punctuation).str.lower()
words

0               this
0         tremendous
0                100
0           varietal
0               wine
             ...
150929        citrus
150929           and
150929           all
150929           for
150929            15
Name: description, Length: 6064847, dtype: object

In [20]:
words.loc[(words.str.len() >= 5) & ~(words.isin(['flavors', 'aromas', 'finish', 'palate', 'drink']))].value_counts().head(10)

description
fruit      56496
acidity    32603
tannins    32186
cherry     30685
black      24599
spice      22658
sweet      21284
notes      19606
fresh      17662
berry      17104
Name: count, dtype: int64

In [22]:
words_france = df.loc[df['country'] == 'France']['description'].str.split().explode().str.strip().str.strip(string.punctuation).str.lower()
words_france.value_counts().head(10)

description
and     40114
the     36107
a       31458
of      21643
is      21338
wine    19709
with    19112
this    16500
it      11587
to       9631
Name: count, dtype: int64

In [25]:
def get_top_words(descs, n=10):
    words = descs.str.split().explode().str.strip().str.strip(string.punctuation).str.lower()
    words = words.loc[(words.str.len() >= 5) & ~(words.isin(['flavors', 'aromas', 'finish', 'palate', 'drink']))]
    return words.value_counts().head(n)

In [26]:
get_top_words(df['description'])

description
fruit      56496
acidity    32603
tannins    32186
cherry     30685
black      24599
spice      22658
sweet      21284
notes      19606
fresh      17662
berry      17104
Name: count, dtype: int64

In [27]:
get_top_words(df.loc[df['country'] == 'France']['description'])

description
fruit        8722
acidity      8641
tannins      6509
fruits       5459
fresh        4217
character    3499
black        3124
texture      3074
years        2957
crisp        2879
Name: count, dtype: int64

In [28]:
get_top_words(df.loc[df['province'] != 'California']['description'])

description
fruit      46517
acidity    22325
tannins    22007
cherry     19473
spice      18572
black      17785
notes      16591
fresh      16221
berry      15499
sweet      12741
Name: count, dtype: int64

In [29]:
get_top_words(df.loc[df['variety'].isin(['Chardonnay', 'Sauvignon Blanc', 'Riesling'])]['description'])

description
fruit         9156
acidity       8367
apple         5893
citrus        5384
chardonnay    4914
crisp         4908
green         4191
notes         4030
pineapple     3859
sweet         3859
Name: count, dtype: int64

In [30]:
get_top_words(df.loc[df['variety'].isin(['Cabernet Sauvignon', 'Syrah', 'Merlot', 'Zinfandel'])]['description'])

description
fruit         9909
tannins       9571
cherry        7927
black         7509
blackberry    6424
cabernet      4864
sweet         4365
chocolate     4257
berry         3707
cassis        3449
Name: count, dtype: int64

In [34]:
df['variety'].loc[df['variety'].str.contains('Ros')].unique()

array(['Rosé', 'Portuguese Rosé', 'Rosado', 'Rosato', 'Tocai Rosso',
       'Roscetto'], dtype=object)

In [35]:
get_top_words(df.loc[df['variety'].isin(['Rosé'])]['description'])

description
acidity       1135
fruit          697
crisp          672
fresh          622
strawberry     534
light          518
raspberry      510
cherry         470
fruity         428
fruits         420
Name: count, dtype: int64

In [38]:
df['variety'].value_counts().head(5).index

Index(['Chardonnay', 'Pinot Noir', 'Cabernet Sauvignon', 'Red Blend',
       'Bordeaux-style Red Blend'],
      dtype='object', name='variety')

In [39]:
get_top_words(df.loc[df['variety'].isin(df['variety'].value_counts().head(5).index)]['description'])

description
fruit       22859
tannins     16007
cherry      13991
acidity     12526
black       11236
cabernet     9480
spice        7910
sweet        7881
blend        7597
shows        7264
Name: count, dtype: int64

In [40]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [41]:
# 37.1

In [42]:
df = pd.read_csv(
    'data/winemag-150k-reviews.csv',
    usecols=['country', 'province', 'description', 'variety', 'points']
)

df

,country,description,points,province,variety
0,US,This tremendous 100% varietal wine hails from ...,96,California,Cabernet Sauvignon
1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",96,Northern Spain,Tinta de Toro
2,US,Mac Watson honors the memory of a wine once ma...,96,California,Sauvignon Blanc
3,US,"This spent 20 months in 30% new French oak, an...",96,Oregon,Pinot Noir
4,France,"This is the top wine from La Bégude, named aft...",95,Provence,Provence red blend
...,...,...,...,...,...
150925,Italy,Many people feel Fiano represents southern Ita...,91,Southern Italy,White Blend
150926,France,"Offers an intriguing nose with ginger, lime an...",91,Champagne,Champagne Blend
150927,Italy,This classic example comes from a cru vineyard...,91,Southern Italy,White Blend
150928,France,"A perfect salmon shade, with scents of peaches...",90,Champagne,Champagne Blend
150929,Italy,More Pinot Grigios should taste like this. A r...,90,Northeastern Italy,Pinot Grigio

In [45]:
df.groupby(by='country')['points'].mean().sort_values(ascending=False).iloc[:10]

country
England     92.888889
Austria     89.276742
France      88.925870
Germany     88.626427
Italy       88.413664
Canada      88.239796
Slovenia    88.234043
Morocco     88.166667
Turkey      88.096154
Portugal    88.057685
Name: points, dtype: float64

In [46]:
# 37.2

In [49]:
df.loc[df['variety'].isin(df['variety'].value_counts().head(10).index)].pivot_table(index=['country'], columns=['variety'], values=['points'], aggfunc='mean')

                                 points                                \
variety        Bordeaux-style Red Blend Cabernet Sauvignon Chardonnay
country
Argentina                     89.575472          85.527745  84.177489
Australia                     88.841463          88.115502  86.727952
Austria                       91.625000          87.750000  90.016393
Brazil                        86.000000          81.000000        NaN
Bulgaria                            NaN          84.812500  86.875000
Canada                        89.000000          88.666667  88.653846
Chile                         89.754717          86.561564  85.246011
China                               NaN                NaN  82.000000
Croatia                             NaN                NaN  85.000000
Cyprus                              NaN          88.000000        NaN
Czech Republic                      NaN          86.000000        NaN
England                             NaN                NaN  94.000000
France                        89.557460          84.080000  89.315353
Germany                             NaN          87.000000  89.166667
Greece                        86.600000          85.837838  85.638889
Hungary                       85.818182          86.666667  83.000000
India                               NaN          82.000000        NaN
Israel                        88.615385          87.753521  86.746479
Italy                         88.600000          89.536680  88.367906
Lebanon                             NaN          82.000000        NaN
Luxembourg                          NaN                NaN        NaN
Macedonia                           NaN          82.000000        NaN
Mexico                        87.500000          83.666667  83.375000
Moldova                       90.000000          84.545455  82.000000
Morocco                             NaN                NaN  88.000000
New Zealand                   88.905405          86.944444  87.810573
Portugal                      89.875000          88.720000  87.642857
Romania                             NaN          85.578947  84.071429
Serbia                              NaN                NaN        NaN
Slovakia                            NaN                NaN        NaN
Slovenia                      89.750000          88.500000  89.000000
South Africa                  89.766129          88.018433  87.091241
Spain                         86.333333          85.689189  84.550725
Switzerland                         NaN                NaN        NaN
Turkey                        86.666667          91.000000  89.000000
US                            89.311681          88.555786  87.729543
Uruguay                             NaN          83.500000  82.000000

                                                                            \
variety            Merlot Pinot Noir  Red Blend   Riesling Sauvignon Blanc
country
Argentina       84.341969  85.058333  88.197059  85.000000       83.295302
Australia       85.258824  86.405263  87.816176  87.790210       86.624060
Austria         89.000000  88.753846  88.890511  90.583955       88.694215
Brazil          83.200000        NaN  84.000000        NaN             NaN
Bulgaria        84.363636  87.400000  89.000000  83.750000       84.400000
Canada          87.875000  89.111111  89.500000  87.564516       87.750000
Chile           84.939189  85.827273  88.683168  85.714286       85.895805
China                 NaN        NaN        NaN        NaN             NaN
Croatia               NaN  84.000000  86.000000        NaN       82.000000
Cyprus                NaN        NaN  85.714286        NaN             NaN
Czech Republic        NaN        NaN        NaN        NaN             NaN
England               NaN        NaN        NaN        NaN             NaN
France          84.971698  89.430777  87.540984  89.063872       88.026882
Germany               NaN  87.075472  87.285714  88.918816       83.000000
Greece          86.142857        NaN  86.050847        NaN       86.526316
Hungary         88.200000  90.000000  84.454545        NaN       86.000000
India                 NaN        NaN        NaN        NaN       89.500000
Israel          86.078125  85.615385  87.760563  90.000000       84.666667
Italy           89.864952  86.000000  89.042238  87.500000       86.517241
Lebanon               NaN        NaN  85.529412        NaN             NaN
Luxembourg            NaN        NaN        NaN  86.000000             NaN
Macedonia             NaN  84.000000  82.500000        NaN             NaN
Mexico          82.000000        NaN  87.500000        NaN       84.400000
Moldova         85.000000  81.000000  85.400000        NaN       84.000000
Morocco               NaN        NaN  89.000000        NaN       88.000000
New Zealand     86.737705  87.731626  89.800000  87.946667       87.287120
Portugal        86.142857  88.928571  87.189189        NaN       85.727273
Romania         85.263158  85.333333  84.600000  82.857143       85.714286
Serbia                NaN        NaN  89.000000  87.500000             NaN
Slovakia              NaN        NaN        NaN  83.666667             NaN
Slovenia        89.000000  88.285714  88.833333  86.666667       86.750000
South Africa    85.825397  88.166667  87.832536  86.400000       86.368421
Spain           84.666667  85.757576  87.483968  82.000000       83.568627
Switzerland     84.500000        NaN        NaN        NaN             NaN
Turkey          88.500000        NaN  87.700000        NaN       89.000000
US              86.630028  88.877273  87.326671  87.397094       86.784223
Uruguay         83.500000  82.000000  85.387097        NaN             NaN


variety             Syrah  Zinfandel
country
Argentina       85.232394        NaN
Australia       91.952381  88.200000
Austria         87.000000        NaN
Brazil                NaN        NaN
Bulgaria        90.000000        NaN
Canada          89.666667        NaN
Chile           87.506739  85.000000
China                 NaN        NaN
Croatia               NaN        NaN
Cyprus                NaN        NaN
Czech Republic        NaN        NaN
England               NaN        NaN
France          89.772926        NaN
Germany               NaN        NaN
Greece          86.733333        NaN
Hungary               NaN        NaN
India                 NaN        NaN
Israel          87.481481  85.000000
Italy           89.246862        NaN
Lebanon               NaN        NaN
Luxembourg            NaN        NaN
Macedonia             NaN        NaN
Mexico          85.500000        NaN
Moldova               NaN        NaN
Morocco         90.000000        NaN
New Zealand     87.674419  90.000000
Portugal        88.482143        NaN
Romania         82.000000        NaN
Serbia                NaN        NaN
Slovakia              NaN        NaN
Slovenia              NaN        NaN
South Africa    88.057143        NaN
Spain           87.548387        NaN
Switzerland           NaN        NaN
Turkey          89.000000        NaN
US              88.359850  86.664819
Uruguay               NaN        NaN

In [50]:
# 37.3

In [51]:
c = df.groupby('country')

In [52]:
c

In [54]:
cnt = c['variety'].nunique()

In [55]:
cnt

country
Albania                     1
Argentina                  65
Australia                  81
Austria                    52
Bosnia and Herzegovina      2
Brazil                      8
Bulgaria                   16
Canada                     29
Chile                      61
China                       2
Croatia                    20
Cyprus                      5
Czech Republic              6
Egypt                       3
England                     2
France                    131
Georgia                     7
Germany                    36
Greece                     43
Hungary                    29
India                       4
Israel                     37
Italy                     177
Japan                       1
Lebanon                     5
Lithuania                   1
Luxembourg                  2
Macedonia                   5
Mexico                     18
Moldova                    18
Montenegro                  1
Morocco                     8
New Zealand                36
Portugal                   78
Romania                    19
Serbia                      6
Slovakia                    1
Slovenia                   28
South Africa               58
South Korea                 1
Spain                     114
Switzerland                 3
Tunisia                     2
Turkey                     21
US                        218
US-France                   1
Ukraine                     2
Uruguay                    11
Name: variety, dtype: int64

In [57]:
points = c['points'].mean()

In [58]:
points

country
Albania                   88.000000
Argentina                 85.996093
Australia                 87.892475
Austria                   89.276742
Bosnia and Herzegovina    84.750000
Brazil                    83.240000
Bulgaria                  85.467532
Canada                    88.239796
Chile                     86.296768
China                     82.000000
Croatia                   86.280899
Cyprus                    85.870968
Czech Republic            85.833333
Egypt                     83.666667
England                   92.888889
France                    88.925870
Georgia                   85.511628
Germany                   88.626427
Greece                    86.117647
Hungary                   87.329004
India                     87.625000
Israel                    87.176190
Italy                     88.413664
Japan                     85.000000
Lebanon                   85.702703
Lithuania                 84.250000
Luxembourg                87.000000
Macedonia                 84.812500
Mexico                    84.761905
Moldova                   84.718310
Montenegro                82.000000
Morocco                   88.166667
New Zealand               87.554217
Portugal                  88.057685
Romania                   84.920863
Serbia                    87.714286
Slovakia                  83.666667
Slovenia                  88.234043
South Africa              87.225421
South Korea               81.500000
Spain                     86.646589
Switzerland               87.250000
Tunisia                   86.000000
Turkey                    88.096154
US                        87.818789
US-France                 88.000000
Ukraine                   84.600000
Uruguay                   84.478261
Name: points, dtype: float64

In [59]:
df1 = pd.concat(objs=[cnt, points], axis=1)
df1

                        variety     points
country
Albania                       1  88.000000
Argentina                    65  85.996093
Australia                    81  87.892475
Austria                      52  89.276742
Bosnia and Herzegovina        2  84.750000
Brazil                        8  83.240000
Bulgaria                     16  85.467532
Canada                       29  88.239796
Chile                        61  86.296768
China                         2  82.000000
Croatia                      20  86.280899
Cyprus                        5  85.870968
Czech Republic                6  85.833333
Egypt                         3  83.666667
England                       2  92.888889
France                      131  88.925870
Georgia                       7  85.511628
Germany                      36  88.626427
Greece                       43  86.117647
Hungary                      29  87.329004
India                         4  87.625000
Israel                       37  87.176190
Italy                       177  88.413664
Japan                         1  85.000000
Lebanon                       5  85.702703
Lithuania                     1  84.250000
Luxembourg                    2  87.000000
Macedonia                     5  84.812500
Mexico                       18  84.761905
Moldova                      18  84.718310
Montenegro                    1  82.000000
Morocco                       8  88.166667
New Zealand                  36  87.554217
Portugal                     78  88.057685
Romania                      19  84.920863
Serbia                        6  87.714286
Slovakia                      1  83.666667
Slovenia                     28  88.234043
South Africa                 58  87.225421
South Korea                   1  81.500000
Spain                       114  86.646589
Switzerland                   3  87.250000
Tunisia                       2  86.000000
Turkey                       21  88.096154
US                          218  87.818789
US-France                     1  88.000000
Ukraine                       2  84.600000
Uruguay                      11  84.478261

In [60]:
df1.corr()

          variety    points
variety  1.000000  0.361241
points   0.361241  1.000000

In [62]:
c['points'].agg(['mean', 'count']).corr()

           mean     count
mean   1.000000  0.236117
count  0.236117  1.000000