In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'total_amount'])
df

         passenger_count  trip_distance  total_amount
0                      1           1.50          9.95
1                      1           2.60         16.30
2                      3           0.00          5.80
3                      5           0.00          7.55
4                      5           0.00         55.55
...                  ...            ...           ...
7667787                1           4.79         23.16
7667788                1           0.00          0.00
7667789                1           0.00          0.00
7667790                1           0.00          0.00
7667791                1           0.00          0.00

[7667792 rows x 3 columns]

In [3]:
len(df) - df.count()

passenger_count    0
trip_distance      0
total_amount       0
dtype: int64

In [14]:
df.sort_values(by=['trip_distance'], ascending=[False]).iloc[:20]['total_amount'].mean().round(2)

np.float64(290.01)

In [15]:
df.sort_values(by=['trip_distance'], ascending=[True]).iloc[-20:]['total_amount'].mean().round(2)

np.float64(290.01)

In [16]:
df.sort_values(by=['trip_distance'], ascending=[True]).tail(20)['total_amount'].mean().round(2)

np.float64(290.01)

In [13]:
df.sort_values(by=['passenger_count', 'trip_distance'], ascending=[True, False]).head(50)['total_amount'].mean()

np.float64(135.49739999999997)

In [17]:
df.sort_values(by=['passenger_count', 'trip_distance'], ascending=[True, False]).head(50)['total_amount'].mean().round(2)

np.float64(135.5)

In [18]:
# 29.1

In [19]:
df.head()

   passenger_count  trip_distance  total_amount
0                1            1.5          9.95
1                1            2.6         16.30
2                3            0.0          5.80
3                5            0.0          7.55
4                5            0.0         55.55

In [20]:
df['amount_per_mile'] = df['total_amount'] / df['trip_distance']

In [21]:
df.head()

   passenger_count  trip_distance  total_amount  amount_per_mile
0                1            1.5          9.95         6.633333
1                1            2.6         16.30         6.269231
2                3            0.0          5.80              inf
3                5            0.0          7.55              inf
4                5            0.0         55.55              inf

In [24]:
df.loc[df['trip_distance'] != 0.0].sort_values(by=['amount_per_mile'], ascending=[False]).iloc[:5]['trip_distance']

2499600    2.40
478791     0.10
7099014    0.01
6403254    0.01
4136499    0.01
Name: trip_distance, dtype: float64

In [25]:
# 29.2

In [26]:
df['amount_per_passenger'] = df['total_amount'] / df['passenger_count']

In [27]:
df.head()

,passenger_count,trip_distance,total_amount,amount_per_mile,amount_per_passenger
0,1,1.5,9.95,6.633333,9.950000
1,1,2.6,16.30,6.269231,16.300000
2,3,0.0,5.80,inf,1.933333
3,5,0.0,7.55,inf,1.510000
4,5,0.0,55.55,inf,11.110000

In [30]:
df.loc[df['passenger_count'] > 1].sort_values(by=['amount_per_passenger'], ascending=[False]).head(10)

,passenger_count,trip_distance,total_amount,amount_per_mile,amount_per_passenger
2972145,2,19.90,589.96,29.646231,294.980
3014027,2,16.60,560.76,33.780723,280.380
3842620,2,110.04,515.82,4.687568,257.910
7593395,2,83.61,449.32,5.373998,224.660
149362,2,17.20,426.80,24.813953,213.400
5726185,2,65.05,416.82,6.407686,208.410
6857368,2,0.00,411.36,inf,205.680
6496403,2,0.00,410.95,inf,205.475
4751745,2,100.78,403.50,4.003771,201.750
1154626,2,0.00,400.80,inf,200.400

In [31]:
# 29.3

In [41]:
df.sort_values(by=['trip_distance'], ascending=[False], ignore_index=True)['total_amount'].loc[:19].mean().round(2)

np.float64(290.01)

In [42]:
df.sort_values(by=['trip_distance'], ascending=[False]).iloc[:20]['total_amount'].mean().round(2)

np.float64(290.01)