In [1]:
import numpy as np
import pandas as pd

In [2]:
import timeit

In [3]:
df = pd.read_csv(
    'data/nyc-parking-violations-2020.csv',
    usecols=[
        'Plate ID',
        'Registration State',
        'Plate Type',
        'Feet From Curb',
        'Vehicle Make',
        'Vehicle Color'
    ],
    low_memory=False
)

df

,Plate ID,Registration State,Plate Type,Vehicle Make,Vehicle Color,Feet From Curb
0,J58JKX,NJ,PAS,HONDA,BK,0
1,KRE6058,PA,PAS,ME/BE,BLK,0
2,444326R,NJ,PAS,LEXUS,BLACK,0
3,F728330,OH,PAS,CHEVR,NaN,0
4,FMY9090,NY,PAS,JEEP,GREY,0
...,...,...,...,...,...,...
12495729,62161MM,NY,COM,FORD,BR,0
12495730,GYE7330,NY,PAS,HONDA,BLK,0
12495731,HNY4802,NY,PAS,FORD,GY,0
12495732,T687081C,NY,PAS,TOYOT,BLK,0
12495733,3497ZN,WA,PAS,UTILI,WHITE,0

In [4]:
df.columns

Index(['Plate ID', 'Registration State', 'Plate Type', 'Vehicle Make',
       'Vehicle Color', 'Feet From Curb'],
      dtype='object')

In [5]:
df.columns = ['pid', 'state', 'ptype', 'make', 'color', 'feet']

In [6]:
df

               pid state ptype   make  color  feet
0           J58JKX    NJ   PAS  HONDA     BK     0
1          KRE6058    PA   PAS  ME/BE    BLK     0
2          444326R    NJ   PAS  LEXUS  BLACK     0
3          F728330    OH   PAS  CHEVR    NaN     0
4          FMY9090    NY   PAS   JEEP   GREY     0
...            ...   ...   ...    ...    ...   ...
12495729   62161MM    NY   COM   FORD     BR     0
12495730   GYE7330    NY   PAS  HONDA    BLK     0
12495731   HNY4802    NY   PAS   FORD     GY     0
12495732  T687081C    NY   PAS  TOYOT    BLK     0
12495733    3497ZN    WA   PAS  UTILI  WHITE     0

[12495734 rows x 6 columns]

In [8]:
%%timeit

len(df) - df.count()

889 ms ± 3.25 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [9]:
len(df) - df.count()

pid         202
state         0
ptype         0
make      62420
color    391982
feet          0
dtype: int64

In [11]:
%%timeit
df.set_index(keys=['state']).sort_index().loc[['NY', 'NJ', 'CT']]

4.72 s ± 28.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [13]:
%%timeit
df.loc[df['state'].isin(['NY', 'NJ', 'CT'])]

474 ms ± 2.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [15]:
%%timeit
df.query('state.isin(["NY", "NJ", "CT"])')

485 ms ± 2.44 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [16]:
%%timeit
df.loc[(df['state'] == 'NY') | (df['state'] == 'NJ') | (df['state'] == 'CT')]

1.13 s ± 7.21 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [18]:
%%timeit
df.query('(state == "NY") | (state == "NJ") | (state == "CT")')

601 ms ± 2.45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [28]:
%timeit df.loc[df['state'] == 'NY']
%timeit df.query('state == "NY"')
%timeit df.loc[df.eval('state == "NY"')]

564 ms ± 4.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
425 ms ± 2.74 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
428 ms ± 6.03 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [29]:
%timeit df.loc[(df['state'] == 'NY') & (df['ptype'] == 'PAS')]
%timeit df.query('state == "NY" and ptype == "PAS"')
%timeit df.loc[df.eval('state == "NY" and ptype == "PAS"')]

741 ms ± 3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
472 ms ± 8.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
468 ms ± 1.75 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [31]:
%timeit df.loc[(df['state'] == 'NY') & (df['ptype'] == 'PAS') & (df['color'] == 'WHITE')]
%timeit df.query('state == "NY" and ptype == "PAS" and color == "WHITE"')
%timeit df.loc[df.eval('state == "NY" and ptype == "PAS" and color == "WHITE"')]

805 ms ± 2.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
345 ms ± 1.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
349 ms ± 9.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [32]:
%timeit df.loc[(df['state'] == 'NY') & (df['ptype'] == 'PAS') & (df['color'] == 'WHITE') & (df['feet'] > 1)]
%timeit df.query('(state == "NY") and (ptype == "PAS") and (color == "WHITE") and (feet > 1)')
%timeit df.loc[df.eval('(state == "NY") and (ptype == "PAS") and (color == "WHITE") and (feet > 1)')]

803 ms ± 5.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
341 ms ± 3.39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
342 ms ± 2.31 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [33]:
%timeit df.loc[(df['state'] == 'NY') & (df['ptype'] == 'PAS') & (df['color'] == 'WHITE') & (df['feet'] > 1) & (df['make'] == 'TOYOTA')]
%timeit df.query('(state == "NY") and (ptype == "PAS") and (color == "WHITE") and (feet > 1) and (make == "TOYOTA")')
%timeit df.loc[df.eval('(state == "NY") and (ptype == "PAS") and (color == "WHITE") and (feet > 1) and (make == "TOYOTA")')]

1.04 s ± 11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
424 ms ± 4.46 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
424 ms ± 1.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [34]:
# 50.1

In [35]:
%timeit df.query('(state == "NY") and (ptype == "PAS") and (color == "WHITE") and (feet > 1) and (make == "TOYOTA")')
%timeit df.query('(state == "NY") & (ptype == "PAS") & (color == "WHITE") & (feet > 1) & (make == "TOYOTA")')

416 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
419 ms ± 1.63 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [36]:
# 50.2

In [37]:
%timeit df.loc[(df['state'] == 'NY') & (df['ptype'] == 'PAS') & (df['color'] == 'WHITE') & (df['feet'] / 3.28 > 1) & (df['make'] == 'TOYOTA')]
%timeit df.query('(state == "NY") and (ptype == "PAS") and (color == "WHITE") and (feet / 3.28 > 1) and (make == "TOYOTA")')

1.03 s ± 13.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
424 ms ± 6.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [38]:
%timeit df.loc[df['feet'] / 3.28 > 1]
%timeit df.query('feet / 3.28 > 1')

21.6 ms ± 102 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
29.5 ms ± 536 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [39]:
# 50.3

In [40]:
%timeit df.loc[(df['state'] == 'NY') & (df['feet'] / 3.28 > 1)]
%timeit df.query('(state == "NY") and (feet / 3.28 > 1)')

285 ms ± 2.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
150 ms ± 998 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)