In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv(
        'https://api.blockchain.info/charts/market-price?format=csv',
        header=None,
        parse_dates=['date'],
        names=['date', 'price']
)
df

          date      price
0   2024-10-22   67363.26
1   2024-10-23   67368.20
2   2024-10-24   66655.68
3   2024-10-25   68162.43
4   2024-10-26   66639.48
..         ...        ...
361 2025-10-18  106466.05
362 2025-10-19  107209.72
363 2025-10-20  108688.24
364 2025-10-21  110576.70
365 2025-10-22  108448.06

[366 rows x 2 columns]

In [5]:
df.loc[df['date'] == df['date'].max(), 'price']

365    108448.06
Name: price, dtype: float64

In [6]:
df.loc[df['price'] == df['price'].min()]

        date     price
4 2024-10-26  66639.48

In [7]:
df.loc[df['price'] == df['price'].max()]

          date      price
350 2025-10-07  124776.68

In [10]:
df.tail(1)[['price']]

         price
365  108448.06

In [11]:
# 19.1

In [13]:
pd.read_csv(
    'https://api.blockchain.info/charts/market-price?format=csv',
    header=None,
    parse_dates=['date'],
    names=['date', 'price']
).tail(1)['price']

365    108448.06
Name: price, dtype: float64

In [14]:
# 19.2

In [15]:
import requests

In [16]:
from io import StringIO

In [19]:
r = requests.get('https://finance.yahoo/quote/%5EGSPC/history?p=%5EGSPC', headers={'User-Agent': 'Mozilla/5.0'})

In [21]:
r.content

b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'