In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv(
        'data/nyc-parking-violations-2020.csv',
        usecols=['Date First Observed', 'Plate ID', 'Registration State', 'Issue Date', 'Vehicle Make', 'Street Name', 'Vehicle Color'],
        parse_dates=['Issue Date']
)
df

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_1482/3746654222.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df = pd.read_csv(

,Plate ID,Registration State,Issue Date,Vehicle Make,Street Name,Date First Observed,Vehicle Color
0,J58JKX,NJ,1972-05-08,HONDA,43 ST,0,BK
1,KRE6058,PA,1977-08-29,ME/BE,UNION ST,0,BLK
2,444326R,NJ,1988-10-03,LEXUS,CLERMONT AVENUE,0,BLACK
3,F728330,OH,1990-01-03,CHEVR,DIVISION AVE,0,NaN
4,FMY9090,NY,1990-02-14,JEEP,GRAND ST,0,GREY
...,...,...,...,...,...,...,...
12495729,62161MM,NY,2040-01-03,FORD,3RD AVE,0,BR
12495730,GYE7330,NY,2045-04-19,HONDA,PELHAM PARK DR,0,BLK
12495731,HNY4802,NY,2049-01-17,FORD,LYDIG AVE,0,GY
12495732,T687081C,NY,2063-12-19,TOYOT,E 68 STREET,0,BLK
12495733,3497ZN,WA,2064-06-04,UTILI,W/S/O 182 STREET,0,WHITE

In [5]:
df = df.set_index(keys=['Issue Date'])

In [6]:
df

,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed,Vehicle Color
Issue Date,,,,,,
1972-05-08,J58JKX,NJ,HONDA,43 ST,0,BK
1977-08-29,KRE6058,PA,ME/BE,UNION ST,0,BLK
1988-10-03,444326R,NJ,LEXUS,CLERMONT AVENUE,0,BLACK
1990-01-03,F728330,OH,CHEVR,DIVISION AVE,0,NaN
1990-02-14,FMY9090,NY,JEEP,GRAND ST,0,GREY
...,...,...,...,...,...,...
2040-01-03,62161MM,NY,FORD,3RD AVE,0,BR
2045-04-19,GYE7330,NY,HONDA,PELHAM PARK DR,0,BLK
2049-01-17,HNY4802,NY,FORD,LYDIG AVE,0,GY
2063-12-19,T687081C,NY,TOYOT,E 68 STREET,0,BLK
2064-06-04,3497ZN,WA,UTILI,W/S/O 182 STREET,0,WHITE

In [10]:
df.loc[('2020-01-02',), 'Vehicle Make'].value_counts().iloc[:3]

Vehicle Make
TOYOT    3829
HONDA    3593
FORD     3164
Name: count, dtype: int64

In [14]:
df.loc[('2020-06-01',), 'Street Name'].value_counts().iloc[:5]

Street Name
WB CONDUIT BLVD @ LI    1068
SB WEST ST @ LEROY S     335
EB HORACE HARDING EX     273
EB QUEENS BLVD @ 82N     245
WB ATLANTIC AVE @ CL     229
Name: count, dtype: int64

In [15]:
df = df.reset_index()

In [16]:
df = df.set_index(keys=['Vehicle Color'])

In [17]:
df

,Issue Date,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed
Vehicle Color,,,,,,
BK,1972-05-08,J58JKX,NJ,HONDA,43 ST,0
BLK,1977-08-29,KRE6058,PA,ME/BE,UNION ST,0
BLACK,1988-10-03,444326R,NJ,LEXUS,CLERMONT AVENUE,0
NaN,1990-01-03,F728330,OH,CHEVR,DIVISION AVE,0
GREY,1990-02-14,FMY9090,NY,JEEP,GRAND ST,0
...,...,...,...,...,...,...
BR,2040-01-03,62161MM,NY,FORD,3RD AVE,0
BLK,2045-04-19,GYE7330,NY,HONDA,PELHAM PARK DR,0
GY,2049-01-17,HNY4802,NY,FORD,LYDIG AVE,0
BLK,2063-12-19,T687081C,NY,TOYOT,E 68 STREET,0
WHITE,2064-06-04,3497ZN,WA,UTILI,W/S/O 182 STREET,0

In [19]:
df.index.unique()

Index([   'BK',   'BLK', 'BLACK',     nan,  'GREY',    'GY',    'WH',   'RED',
        'GRAY',   'TAN',
       ...
       'GYHNU',   'BLF',   'BL9', 'LTBR0',   'BK;', 'GLKPP',    '';', 'WHGY8',
        'ORYW',    'CH'],
      dtype='object', name='Vehicle Color', length=1897)

In [32]:
df.loc[[('BLUE'), ('RED')], ('Vehicle Make')].value_counts().iloc[:1]

Vehicle Make
HONDA    39353
Name: count, dtype: int64

In [33]:
# 21.1

In [40]:
df = df.reset_index().set_index(keys=['Issue Date']).sort_index()

In [41]:
df

,Vehicle Color,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed
Issue Date,,,,,,
1972-05-08,BK,J58JKX,NJ,HONDA,43 ST,0
1977-08-29,BLK,KRE6058,PA,ME/BE,UNION ST,0
1988-10-03,BLACK,444326R,NJ,LEXUS,CLERMONT AVENUE,0
1990-01-03,NaN,F728330,OH,CHEVR,DIVISION AVE,0
1990-02-14,GREY,FMY9090,NY,JEEP,GRAND ST,0
...,...,...,...,...,...,...
2040-01-03,BR,62161MM,NY,FORD,3RD AVE,0
2045-04-19,BLK,GYE7330,NY,HONDA,PELHAM PARK DR,0
2049-01-17,GY,HNY4802,NY,FORD,LYDIG AVE,0
2063-12-19,BLK,T687081C,NY,TOYOT,E 68 STREET,0
2064-06-04,WHITE,3497ZN,WA,UTILI,W/S/O 182 STREET,0

In [45]:
df.loc[('2020-01-02'):('2020-01-10'), 'Vehicle Make'].value_counts()

Vehicle Make
FORD     38936
TOYOT    37073
HONDA    35944
NISSA    29573
CHEVR    20004
         ...
FOUR         1
I NFI        1
ZENGH        1
WPRK         1
STUDE        1
Name: count, Length: 574, dtype: int64

In [46]:
# 21.2

In [47]:
df.head()

,Vehicle Color,Plate ID,Registration State,Vehicle Make,Street Name,Date First Observed
Issue Date,,,,,,
1972-05-08,BK,J58JKX,NJ,HONDA,43 ST,0
1977-08-29,BLK,KRE6058,PA,ME/BE,UNION ST,0
1988-10-03,BLACK,444326R,NJ,LEXUS,CLERMONT AVENUE,0
1990-01-03,NaN,F728330,OH,CHEVR,DIVISION AVE,0
1990-02-14,GREY,FMY9090,NY,JEEP,GRAND ST,0

In [49]:
df['Plate ID'].value_counts()

Plate ID
BLANKPLATE    8882
2704819       1535
86107MM       1429
2703289       1364
NS            1189
              ...
0ASBR8           1
GSG6485          1
HAS7271          1
BATMAN01         1
T64528C          1
Name: count, Length: 3245467, dtype: int64

In [50]:
df = df.reset_index().set_index(keys=['Plate ID']).sort_index()
df

,Issue Date,Vehicle Color,Registration State,Vehicle Make,Street Name,Date First Observed
Plate ID,,,,,,
000000,2020-02-19,BLACK,PA,CADIL,60th St,0
000000,2019-08-09,BLACK,PA,CADIL,Bay 22nd St,0
000000,2019-11-22,BLACK,PA,NS/OT,College Point Blvd,0
00000K,2020-02-15,BLACK,VA,BMW,Duffield St,0
00004,2019-08-31,SILVE,PA,HONDA,Fulton St,0
...,...,...,...,...,...,...
NaN,2020-04-18,GREY,NY,NISSA,Reservoir Oval East,0
NaN,2020-04-18,GREY,NY,NISSA,Reservoir Oval East,0
NaN,2020-04-18,GREY,NY,NISSA,Reservoir Oval East,0
NaN,2020-05-16,BLACK,NJ,ME/BE,Leggett Ave,0
NaN,2020-06-11,NaN,NY,NaN,NaN,0

In [53]:
df.loc['2704819', 'Registration State'].value_counts()

Registration State
IN    1527
NJ       5
NY       2
ME       1
Name: count, dtype: int64

In [54]:
# 21.3

In [55]:
df['Date First Observed'].unique()

array([       0, 20190727, 20191113, 20200211, 20190701, 20190808,
       20190703, 20190708, 20190709, 20190910, 20190723, 20200310,
       20200115, 20191202, 20200219, 20190705, 20191107, 20191015,
       20191005, 20190628, 20191122, 20190810, 20191210, 20200104,
       20190818, 20190710, 20190819, 20200226, 20200311, 20190911,
       20191121, 20190904, 20191207, 20191125, 20191112, 20190626,
       20190815, 20200127, 20190909, 20190724, 20190627, 20191030,
       20200527, 20200608, 20200207, 20200220, 20200122, 20191007,
       20190903, 20190802, 20191012, 20191216, 20190715, 20190717,
       20190913, 20191011, 20190817, 20190826, 20200223, 20200312,
       20191105, 20191004, 20200130, 20190902, 20190930, 20190718,
       20200228, 20200117, 20200124, 20200213, 20200121, 20200206,
       20200221, 20190916, 20200305, 20191213, 20191230, 20191203,
       20190814, 20200609, 20190816, 20190830, 20190726, 20200128,
       20190813, 20200526, 20200605, 20200612, 20200618, 20200617,
       20200521, 20191130, 20200309, 20200217, 20191220, 20190918,
       20200123, 20200210, 20190711, 20190731, 20190828, 20190729,
       20200313, 20190725, 20200314, 20200107, 20190925, 20190821,
       20190924, 20190823, 20200407, 20190702, 20190809, 20191114,
       20200611, 20190801, 20191102, 20191024, 20200205, 20191025,
       20191023, 20200208, 20200523, 20191227, 20200303, 20200126,
       20190912, 20191224, 20191104, 20191029, 20200430, 20191019,
       20200131, 20200215, 20200108, 20191211, 20190907, 20190706,
       20190629, 20191001, 20190905, 20191116, 20191231, 20191101,
       20191106, 20191119, 20190919, 20190730, 20190719, 20191021,
       20200229, 20200214, 20190807, 20190822, 20190713, 20190617,
       20191127, 20191214, 20200218, 20191204, 20200113, 20200203,
       20190812, 20191020, 20200222, 20191010, 20191229, 20191027,
       20191008, 20191003, 20190901, 20200307, 20200119, 20191009,
       20200216, 20190928, 20200110, 20191014, 20200204, 20190922,
       20200224, 20191226, 20200326, 20200212, 20191126, 20191118,
       20191002, 20191026, 20191115, 20200103, 20200129, 20191018,
       20191022, 20191120, 20190923, 20191108, 20190820, 20190914,
       20200118, 20200304, 20190917, 20190926, 20191031, 20191123,
       20200320, 20200114, 20191206, 20191205, 20191109, 20190831,
       20200125, 20190803, 20200306, 20200317, 20190716, 20200318,
       20190906, 20200109, 20190806, 20200106, 20200225, 20190824,
       20190920, 20191016, 20190805, 20191028, 20200528, 20200116,
       20191218, 20200302, 20200321, 20191223, 20191209, 20190722,
       20200227, 20190827, 20190712, 20200506, 20200507, 20191017,
       20190720, 20191111, 20191217, 20200319, 20200530, 20190927,
       20200316, 20200120, 20200623, 20200417, 20200409, 20200423,
       20200410, 20191212, 20191219, 20200604, 20200111, 20190915,
       20200625, 20190829, 20191129, 20190610, 20200209, 20190613,
       20191228, 20200610, 20200414, 20200323, 20200102, 20190622,
       20200406, 20190619, 20200416, 20200616, 20190621, 20200201,
       20200330, 20200324, 20200624, 20190804, 20190707, 20200622,
       20190921, 20191221, 20190618, 20190614, 20200501, 20200503,
       20200426, 20200425, 20200101, 20200619, 20200519, 20200518,
       20200520, 20200325, 20200514, 20191110, 20200606, 20200603,
       20200403, 20190721, 20200615, 20200529, 20200620, 20190620,
       20190625, 20190908, 20200522, 20200331, 20200421, 20200429,
       20191215, 20190607, 20200509, 20200419, 20190811, 20191201,
       20200412, 20190623, 20200411, 20200502, 20200513, 20200202,
       20190624, 20200420, 20190612, 20200422, 20200401, 20200418,
       20190728, 20200301, 20200424, 20191222, 20200614, 20190704,
       20200515, 20190521, 20200601, 20190714, 20200308, 20200404,
       20200329, 20190419, 20191013, 20200524, 20200327, 20190630,
       20200408, 20200602, 20190604, 20200112, 20200613, 20200517,
       20200511, 20200415, 20191103, 20200512, 20200505, 20200427,
       20190611, 20190616, 20200508, 20200516, 20200405, 20200105,
       20191208, 20201219, 20190123, 20190615, 20201213, 20190929,
       20201021, 20200428, 20200328, 20190129, 20200504, 20200402,
       20180819, 20191117, 20200322, 20200315, 20200413, 20200230,
       20200510, 20190825, 20190426, 20191006, 20190606, 20191124,
       20210530, 20190517, 20200525, 20180812, 20191225, 20200607,
       20200531, 20190531, 20191128, 20201022, 20190321, 20190113,
       20200727, 20190605, 20190111, 20250405, 20200707, 20190519,
       20170303, 20210214, 20190404, 20300128, 20181227, 20170912,
       20210312, 20190507, 20170709, 20250325, 20160614, 20190204,
       20190608, 20200703, 20210221, 20190510, 20130804, 20300129,
       20200930, 20220412, 20300326, 20191131, 20200926, 20190102,
       20200920, 20171129, 20190525, 20190409, 20190417, 20170216,
       20220602, 20180928, 20201230, 20201119, 20190523, 20290629,
       20201128, 20210517, 20190224, 20190107, 20211004, 20201209,
       20200916, 20200813, 20190603, 20190430, 20181129, 20200731,
       20190609, 20110701, 20181119, 20090630, 20180818, 20190527,
       20201127, 20190212, 20190602])

In [56]:
df['Date First Observed'].nunique()

465

In [57]:
len(df)

12495734

In [58]:
df['Issue Date'].nunique()

1475