In [1]:
import numpy as np
import pandas as pd

In [2]:
data_words = []
with open('data/alice-in-wonderland.txt', 'r') as f:
    for line in f:
        data_words += line.strip().split()

In [3]:
data_words

['\ufeffThe',
 'Project',
 'Gutenberg',
 'EBook',
 'of',
 'Alice',
 'in',
 'Wonderland,',
 'by',
 'Lewis',
 'Carroll',
 'This',
 'eBook',
 'is',
 'for',
 'the',
 'use',
 'of',
 'anyone',
 'anywhere',
 'at',
 'no',
 'cost',
 'and',
 'with',
 'almost',
 'no',
 'restrictions',
 'whatsoever.',
 'You',
 'may',
 'copy',
 'it,',
 'give',
 'it',
 'away',
 'or',
 're-use',
 'it',
 'under',
 'the',
 'terms',
 'of',
 'the',
 'Project',
 'Gutenberg',
 'License',
 'included',
 'with',
 'this',
 'eBook',
 'or',
 'online',
 'at',
 'www.gutenberg.org',
 'Title:',
 'Alice',
 'in',
 'Wonderland',
 'Author:',
 'Lewis',
 'Carroll',
 'Illustrator:',
 'Gordon',
 'Robinson',
 'Release',
 'Date:',
 'August',
 '12,',
 '2006',
 '[EBook',
 '#19033]',
 'Language:',
 'English',
 '***',
 'START',
 'OF',
 'THIS',
 'PROJECT',
 'GUTENBERG',
 'EBOOK',
 'ALICE',
 'IN',
 'WONDERLAND',
 '***',
 'Produced',
 'by',
 'Jason',
 'Isbell,',
 'Irma',
 'Spehar,',
 'and',
 'the',
 'Online',
 'Distributed',
 'Proofreading',
 'Team',
 'at',
 'http://www.pgdp.net',
 '[Illustration:',
 'Alice',
 'in',
 'the',
 'Room',
 'of',
 'the',
 'Duchess.]',
 '_THE',
 '"STORYLAND"',
 'SERIES_',
 "ALICE'S",
 'ADVENTURES',
 'IN',
 'WONDERLAND',
 "SAM'L",
 'GABRIEL',
 'SONS',
 '&',
 'COMPANY',
 'NEW',
 'YORK',
 'Copyright,',
 '1916,',
 'by',
 "SAM'L",
 'GABRIEL',
 'SONS',
 '&',
 'COMPANY',
 'NEW',
 'YORK',
 "ALICE'S",
 'ADVENTURES',
 'IN',
 'WONDERLAND',
 '[Illustration]',
 'I--DOWN',
 'THE',
 'RABBIT-HOLE',
 'Alice',
 'was',
 'beginning',
 'to',
 'get',
 'very',
 'tired',
 'of',
 'sitting',
 'by',
 'her',
 'sister',
 'on',
 'the',
 'bank,',
 'and',
 'of',
 'having',
 'nothing',
 'to',
 'do.',
 'Once',
 'or',
 'twice',
 'she',
 'had',
 'peeped',
 'into',
 'the',
 'book',
 'her',
 'sister',
 'was',
 'reading,',
 'but',
 'it',
 'had',
 'no',
 'pictures',
 'or',
 'conversations',
 'in',
 'it,',
 '"and',
 'what',
 'is',
 'the',
 'use',
 'of',
 'a',
 'book,"',
 'thought',
 'Alice,',
 '"without',
 'pictures',
 'or',
 'conversations?"',
 'So',
 'she',
 'was',
 'considering',
 'in',
 'her',
 'own',
 'mind',
 '(as',
 'well',
 'as',
 'she',
 'could,',
 'for',
 'the',
 'day',
 'made',
 'her',
 'feel',
 'very',
 'sleepy',
 'and',
 'stupid),',
 'whether',
 'the',
 'pleasure',
 'of',
 'making',
 'a',
 'daisy-chain',
 'would',
 'be',
 'worth',
 'the',
 'trouble',
 'of',
 'getting',
 'up',
 'and',
 'picking',
 'the',
 'daisies,',
 'when',
 'suddenly',
 'a',
 'White',
 'Rabbit',
 'with',
 'pink',
 'eyes',
 'ran',
 'close',
 'by',
 'her.',
 'There',
 'was',
 'nothing',
 'so',
 'very',
 'remarkable',
 'in',
 'that,',
 'nor',
 'did',
 'Alice',
 'think',
 'it',
 'so',
 'very',
 'much',
 'out',
 'of',
 'the',
 'way',
 'to',
 'hear',
 'the',
 'Rabbit',
 'say',
 'to',
 'itself,',
 '"Oh',
 'dear!',
 'Oh',
 'dear!',
 'I',
 'shall',
 'be',
 'too',
 'late!"',
 'But',
 'when',
 'the',
 'Rabbit',
 'actually',
 'took',
 'a',
 'watch',
 'out',
 'of',
 'its',
 'waistcoat-pocket',
 'and',
 'looked',
 'at',
 'it',
 'and',
 'then',
 'hurried',
 'on,',
 'Alice',
 'started',
 'to',
 'her',
 'feet,',
 'for',
 'it',
 'flashed',
 'across',
 'her',
 'mind',
 'that',
 'she',
 'had',
 'never',
 'before',
 'seen',
 'a',
 'rabbit',
 'with',
 'either',
 'a',
 'waistcoat-pocket,',
 'or',
 'a',
 'watch',
 'to',
 'take',
 'out',
 'of',
 'it,',
 'and,',
 'burning',
 'with',
 'curiosity,',
 'she',
 'ran',
 'across',
 'the',
 'field',
 'after',
 'it',
 'and',
 'was',
 'just',
 'in',
 'time',
 'to',
 'see',
 'it',
 'pop',
 'down',
 'a',
 'large',
 'rabbit-hole,',
 'under',
 'the',
 'hedge.',
 'In',
 'another',
 'moment,',
 'down',
 'went',
 'Alice',
 'after',
 'it!',
 '[Illustration]',
 'The',
 'rabbit-hole',
 'went',
 'straight',
 'on',
 'like',
 'a',
 'tunnel',
 'for',
 'some',
 'way',
 'and',
 'then',
 'dipped',
 'suddenly',
 'down,',
 'so',
 'suddenly',
 'that',
 'Alice',
 'had',
 'not',
 'a',
 'moment',
 'to',
 'think',
 'about',
 'stopping',
 'herself',
 'before',
 'she',
 'found',
 'herself',
 'falling',
 'down',
 'what',
 'seemed',
 'to',
 'be',
 'a',
 'very',
 'deep',
 'well.',
 'Either',
 'the',
 'well',
 'was',
 'very',
 'deep,',
 'or',
 'she',
 'fell',
 'very',
 'slowly,',
 'for',
 'she',
 'had',
 'plenty',
 'of',
 'time,',
 'as',
 'she',
 'went',
 'down,',
 'to',
 'look',
 'about',
 'her.',
 'First,',
 'she',
 'tried',
 'to',
 'make',
 'out',
 'what',
 'she',
 'was',
 'coming',
 'to,',
 'but',
 'it',
 'was',
 'too',
 'dark',
 'to',
 'see',
 'anything;',
 'then',
 'she',
 'looked',
 'at',
 'the',
 'sides',
 'of',
 'the',
 'well',
 'and',
 'noticed',
 'that',
 'they',
 'were',
 'filled',
 'with',
 'cupboards',
 'and',
 'book-shelves;',
 'here',
 'and',
 'there',
 'she',
 'saw',
 'maps',
 'and',
 'pictures',
 'hung',
 'upon',
 'pegs.',
 'She',
 'took',
 'down',
 'a',
 'jar',
 'from',
 'one',
 'of',
 'the',
 'shelves',
 'as',
 'she',
 'passed.',
 'It',
 'was',
 'labeled',
 '"ORANGE',
 'MARMALADE,"',
 'but,',
 'to',
 'her',
 'great',
 'disappointment,',
 'it',
 'was',
 'empty;',
 'she',
 'did',
 'not',
 'like',
 'to',
 'drop',
 'the',
 'jar,',
 'so',
 'managed',
 'to',
 'put',
 'it',
 'into',
 'one',
 'of',
 'the',
 'cupboards',
 'as',
 'she',
 'fell',
 'past',
 'it.',
 'Down,',
 'down,',
 'down!',
 'Would',
 'the',
 'fall',
 'never',
 'come',
 'to',
 'an',
 'end?',
 'There',
 'was',
 'nothing',
 'else',
 'to',
 'do,',
 'so',
 'Alice',
 'soon',
 'began',
 'talking',
 'to',
 'herself.',
 '"Dinah\'ll',
 'miss',
 'me',
 'very',
 'much',
 'to-night,',
 'I',
 'should',
 'think!"',
 '(Dinah',
 'was',
 'the',
 'cat.)',
 '"I',
 'hope',
 "they'll",
 'remember',
 'her',
 'saucer',
 'of',
 'milk',
 'at',
 'tea-time.',
 'Dinah,',
 'my',
 'dear,',
 'I',
 'wish',
 'you',
 'were',
 'down',
 'here',
 'with',
 'me!"',
 'Alice',
 'felt',
 'that',
 'she',
 'was',
 'dozing',
 'off,',
 'when',
 'suddenly,',
 'thump!',
 'thump!',
 'down',
 'she',
 'came',
 'upon',
 'a',
 'heap',
 'of',
 'sticks',
 'and',
 'dry',
 'leaves,',
 'and',
 'the',
 'fall',
 'was',
 'over.',
 'Alice',
 'was',
 'not',
 'a',
 'bit',
 'hurt,',
 'and',
 'she',
 'jumped',
 'up',
 'in',
 'a',
 'moment.',
 'She',
 'looked',
 'up,',
 'but',
 'it',
 'was',
 'all',
 'dark',
 'overhead;',
 'before',
 'her',
 'was',
 'another',
 'long',
 'passage',
 'and',
 'the',
 'White',
 'Rabbit',
 'was',
 'still',
 'in',
 'sight,',
 'hurrying',
 'down',
 'it.',
 'There',
 'was',
 'not',
 'a',
 'moment',
 'to',
 'be',
 'lost.',
 'Away',
 'went',
 'Alice',
 'like',
 'the',
 'wind',
 'and',
 'was',
 'just',
 'in',
 'time',
 'to',
 'hear',
 'it',
 'say,',
 'as',
 'it',
 'turned',
 'a',
 'corner,',
 '"Oh,',
 'my',
 'ears',
 'and',
 'whiskers,',
 'how',
 'late',
 "it's",
 'getting!"',
 'She',
 'was',
 'close',
 'behind',
 'it',
 'when',
 'she',
 'turned',
 'the',
 'corner,',
 'but',
 'the',
 'Rabbit',
 'was',
 'no',
 'longer',
 'to',
 'be',
 'seen.',
 'She',
 'found',
 'herself',
 'in',
 'a',
 'long,',
 'low',
 'hall,',
 'which',
 'was',
 'lit',
 'up',
 'by',
 'a',
 'row',
 'of',
 'lamps',
 'hanging',
 'from',
 'the',
 'roof.',
 'There',
 'were',
 'doors',
 'all',
 "'round",
 'the',
 'hall,',
 'but',
 'they',
 'were',
 'all',
 'locked;',
 'and',
 'when',
 'Alice',
 'had',
 'been',
 'all',
 'the',
 'way',
 'down',
 'one',
 'side',
 'and',
 'up',
 'the',
 'other,',
 'trying',
 'every',
 'door,',
 'she',
 'walked',
 'sadly',
 'down',
 'the',
 'middle,',
 'wondering',
 'how',
 'she',
 'was',
 'ever',
 'to',
 'get',
 'out',
 'again.',
 'Suddenly',
 'she',
 'came',
 'upon',
 'a',
 'little',
 'table,',
 'all',
 'made',
 'of',
 'solid',
 'glass.',
 'There',
 'was',
 'nothing',
 'on',
 'it',
 'but',
 'a',
 'tiny',
 'golden',
 'key,',
 'and',
 "Alice's",
 'first',
 'idea',
 'was',
 'that',
 'this',
 'might',
 'belong',
 'to',
 'one',
 'of',
 'the',
 'doors',
 'of',
 'the',
 'hall;',
 'but,',
 'alas!',
 'either',
 'the',
 'locks',
 'were',
 'too',
 'large,',
 'or',
 'the',
 'key',
 'was',
 'too',
 'small,',
 'but,',
 'at',
 'any',
 'rate,',
 'it',
 'would',
 'not',
 'open',
 'any',
 'of',
 'them.',
 'However,',
 'on',
 'the',
 'second',
 'time',
 "'round,",
 'she',
 'came',
 'upon',
 'a',
 'low',
 'curtain',
 'she',
 'had',
 'not',
 'noticed',
 'before,',
 'and',
 'behind',
 'it',
 'was',
 'a',
 'little',
 'door',
 'about',
 'fifteen',
 'inches',
 'high.',
 'She',
 'tried',
 'the',
 'little',
 'golden',
 'key',
 'in',
 'the',
 'lock,',
 'and',
 'to',
 'her',
 'great',
 'delight,',
 'it',
 'fitted!',
 '[Illustration]',
 'Alice',
 'opened',
 'the',
 'door',
 'and',
 'found',
 'that',
 'it',
 'led',
 'into',
 'a',
 'small',
 'passage,',
 'not',
 'much',
 'larger',
 'than',
 'a',
 'rat-hole;',
 'she',
 'knelt',
 'down',
 'and',
 'looked',
 'along',
 'the',
 'passage',
 'into',
 'the',
 'loveliest',
 'garden',
 'you',
 'ever',
 'saw.',
 'How',
 'she',
 'longed',
 'to',
 'get',
 'out',
 'of',
 'that',
 'dark',
 'hall',
 'and',
 'wander',
 'about',
 'among',
 'those',
 'beds',
 'of',
 'bright',
 'flowers',
 'and',
 'those',
 'cool',
 'fountains,',
 'but',
 'she',
 'could',
 'not',
 'even',
 'get',
 'her',
 'head',
 'through',
 'the',
 'doorway.',
 '"Oh,"',
 'said',
 'Alice,',
 '"how',
 'I',
 'wish',
 'I',
 'could',
 'shut',
 'up',
 'like',
 'a',
 'telescope!',
 'I',
 'think',
 'I',
 'could,',
 'if',
 'I',
 'only',
 'knew',
 'how',
 'to',
 'begin."',
 'Alice',
 'went',
 'back',
 'to',
 'the',
 'table,',
 'half',
 'hoping',
 'she',
 'might',
 'find',
 'another',
 'key',
 'on',
 ...]

In [4]:
len(data_words)

12763

In [5]:
s = pd.Series(data=data_words)
s

0             ﻿The
1          Project
2        Gutenberg
3            EBook
4               of
           ...
12758           to
12759         hear
12760        about
12761          new
12762      eBooks.
Length: 12763, dtype: object

In [7]:
s.value_counts()[:10]

the     732
and     362
a       321
to      311
of      300
in      211
she     197
was     160
said    129
it      122
Name: count, dtype: int64

In [9]:
s.str.lower().value_counts()[:10]

the    792
and    379
a      325
to     318
of     313
she    232
in     222
was    160
you    141
it     136
Name: count, dtype: int64

In [10]:
import string

In [12]:
s.str.strip(string.punctuation).str.lower().value_counts()[:10]

the    807
and    404
a      328
to     327
of     318
she    237
in     227
it     183
you    171
was    168
Name: count, dtype: int64

In [15]:
len(s.loc[s.str.istitle()])

1531

In [18]:
len(s.loc[s.str.strip(string.punctuation + '"' + "'").str.istitle()])

1531

In [21]:
s.str.lower().str.count('[aeiou]')

0        1
1        2
2        3
3        3
4        1
        ..
12758    1
12759    2
12760    3
12761    1
12762    3
Length: 12763, dtype: int64

In [22]:
s.str.lower().str.count('[aeiou]').mean()

np.float64(1.66379377889211)

In [25]:
len(s.loc[s.str.contains(r'^[A-Z]\w*$', regex=True)])

1100

In [29]:
s.loc[(s.str.istitle()) & ~(s.str.contains(r'^[A-Z]\w*$', regex=True))]

0                ﻿The
7         Wonderland,
55             Title:
59            Author:
62       Illustrator:
             ...
12573            U.S.
12626              S.
12687            U.S.
12694           Thus,
12742     Foundation,
Length: 605, dtype: object

In [31]:
len(s.loc[s.str.contains(r'^[A-Z].*$', regex=True)])

1532

In [32]:
s.loc[~(s.str.istitle()) & (s.str.contains(r'^[A-Z].*$', regex=True))]

3                EBook
75               START
76                  OF
77                THIS
78             PROJECT
             ...
12634     Gutenberg-tm
12657     Gutenberg-tm
12668     Gutenberg-tm
12719               PG
12730    Gutenberg-tm,
Length: 331, dtype: object

In [33]:
# 36.1

In [49]:
s.str.strip(string.punctuation).loc[s.str.strip(string.punctuation).str.isdigit()].astype(int).mean()

np.float64(8030.851851851852)

In [50]:
# 36.2

In [68]:
alice_words = s.str.strip().str.strip(string.punctuation + "'" + '"').to_frame()

In [69]:
alice_words.columns = ['word']

In [70]:
alice_words

            word
0           ﻿The
1        Project
2      Gutenberg
3          EBook
4             of
...          ...
12758         to
12759       hear
12760      about
12761        new
12762     eBooks

[12763 rows x 1 columns]

In [71]:
w = []
with open('data/words.txt', 'r') as f:
    for line in f:
        w += line.strip().split()

In [72]:
w

['A',
 'a',
 'aa',
 'aal',
 'aalii',
 'aam',
 'Aani',
 'aardvark',
 'aardwolf',
 'Aaron',
 'Aaronic',
 'Aaronical',
 'Aaronite',
 'Aaronitic',
 'Aaru',
 'Ab',
 'aba',
 'Ababdeh',
 'Ababua',
 'abac',
 'abaca',
 'abacate',
 'abacay',
 'abacinate',
 'abacination',
 'abaciscus',
 'abacist',
 'aback',
 'abactinal',
 'abactinally',
 'abaction',
 'abactor',
 'abaculus',
 'abacus',
 'Abadite',
 'abaff',
 'abaft',
 'abaisance',
 'abaiser',
 'abaissed',
 'abalienate',
 'abalienation',
 'abalone',
 'Abama',
 'abampere',
 'abandon',
 'abandonable',
 'abandoned',
 'abandonedly',
 'abandonee',
 'abandoner',
 'abandonment',
 'Abanic',
 'Abantes',
 'abaptiston',
 'Abarambo',
 'Abaris',
 'abarthrosis',
 'abarticular',
 'abarticulation',
 'abas',
 'abase',
 'abased',
 'abasedly',
 'abasedness',
 'abasement',
 'abaser',
 'Abasgi',
 'abash',
 'abashed',
 'abashedly',
 'abashedness',
 'abashless',
 'abashlessly',
 'abashment',
 'abasia',
 'abasic',
 'abask',
 'Abassin',
 'abastardize',
 'abatable',
 'abate',
 'abatement',
 'abater',
 'abatis',
 'abatised',
 'abaton',
 'abator',
 'abattoir',
 'Abatua',
 'abature',
 'abave',
 'abaxial',
 'abaxile',
 'abaze',
 'abb',
 'Abba',
 'abbacomes',
 'abbacy',
 'Abbadide',
 'abbas',
 'abbasi',
 'abbassi',
 'Abbasside',
 'abbatial',
 'abbatical',
 'abbess',
 'abbey',
 'abbeystede',
 'Abbie',
 'abbot',
 'abbotcy',
 'abbotnullius',
 'abbotship',
 'abbreviate',
 'abbreviately',
 'abbreviation',
 'abbreviator',
 'abbreviatory',
 'abbreviature',
 'Abby',
 'abcoulomb',
 'abdal',
 'abdat',
 'Abderian',
 'Abderite',
 'abdest',
 'abdicable',
 'abdicant',
 'abdicate',
 'abdication',
 'abdicative',
 'abdicator',
 'Abdiel',
 'abditive',
 'abditory',
 'abdomen',
 'abdominal',
 'Abdominales',
 'abdominalian',
 'abdominally',
 'abdominoanterior',
 'abdominocardiac',
 'abdominocentesis',
 'abdominocystic',
 'abdominogenital',
 'abdominohysterectomy',
 'abdominohysterotomy',
 'abdominoposterior',
 'abdominoscope',
 'abdominoscopy',
 'abdominothoracic',
 'abdominous',
 'abdominovaginal',
 'abdominovesical',
 'abduce',
 'abducens',
 'abducent',
 'abduct',
 'abduction',
 'abductor',
 'Abe',
 'abeam',
 'abear',
 'abearance',
 'abecedarian',
 'abecedarium',
 'abecedary',
 'abed',
 'abeigh',
 'Abel',
 'abele',
 'Abelia',
 'Abelian',
 'Abelicea',
 'Abelite',
 'abelite',
 'Abelmoschus',
 'abelmosk',
 'Abelonian',
 'abeltree',
 'Abencerrages',
 'abenteric',
 'abepithymia',
 'Aberdeen',
 'aberdevine',
 'Aberdonian',
 'Aberia',
 'aberrance',
 'aberrancy',
 'aberrant',
 'aberrate',
 'aberration',
 'aberrational',
 'aberrator',
 'aberrometer',
 'aberroscope',
 'aberuncator',
 'abet',
 'abetment',
 'abettal',
 'abettor',
 'abevacuation',
 'abey',
 'abeyance',
 'abeyancy',
 'abeyant',
 'abfarad',
 'abhenry',
 'abhiseka',
 'abhominable',
 'abhor',
 'abhorrence',
 'abhorrency',
 'abhorrent',
 'abhorrently',
 'abhorrer',
 'abhorrible',
 'abhorring',
 'Abhorson',
 'abidal',
 'abidance',
 'abide',
 'abider',
 'abidi',
 'abiding',
 'abidingly',
 'abidingness',
 'Abie',
 'Abies',
 'abietate',
 'abietene',
 'abietic',
 'abietin',
 'Abietineae',
 'abietineous',
 'abietinic',
 'Abiezer',
 'Abigail',
 'abigail',
 'abigailship',
 'abigeat',
 'abigeus',
 'abilao',
 'ability',
 'abilla',
 'abilo',
 'abintestate',
 'abiogenesis',
 'abiogenesist',
 'abiogenetic',
 'abiogenetical',
 'abiogenetically',
 'abiogenist',
 'abiogenous',
 'abiogeny',
 'abiological',
 'abiologically',
 'abiology',
 'abiosis',
 'abiotic',
 'abiotrophic',
 'abiotrophy',
 'Abipon',
 'abir',
 'abirritant',
 'abirritate',
 'abirritation',
 'abirritative',
 'abiston',
 'Abitibi',
 'abiuret',
 'abject',
 'abjectedness',
 'abjection',
 'abjective',
 'abjectly',
 'abjectness',
 'abjoint',
 'abjudge',
 'abjudicate',
 'abjudication',
 'abjunction',
 'abjunctive',
 'abjuration',
 'abjuratory',
 'abjure',
 'abjurement',
 'abjurer',
 'abkar',
 'abkari',
 'Abkhas',
 'Abkhasian',
 'ablach',
 'ablactate',
 'ablactation',
 'ablare',
 'ablastemic',
 'ablastous',
 'ablate',
 'ablation',
 'ablatitious',
 'ablatival',
 'ablative',
 'ablator',
 'ablaut',
 'ablaze',
 'able',
 'ableeze',
 'ablegate',
 'ableness',
 'ablepharia',
 'ablepharon',
 'ablepharous',
 'Ablepharus',
 'ablepsia',
 'ableptical',
 'ableptically',
 'abler',
 'ablest',
 'ablewhackets',
 'ablins',
 'abloom',
 'ablow',
 'ablude',
 'abluent',
 'ablush',
 'ablution',
 'ablutionary',
 'abluvion',
 'ably',
 'abmho',
 'Abnaki',
 'abnegate',
 'abnegation',
 'abnegative',
 'abnegator',
 'Abner',
 'abnerval',
 'abnet',
 'abneural',
 'abnormal',
 'abnormalism',
 'abnormalist',
 'abnormality',
 'abnormalize',
 'abnormally',
 'abnormalness',
 'abnormity',
 'abnormous',
 'abnumerable',
 'Abo',
 'aboard',
 'Abobra',
 'abode',
 'abodement',
 'abody',
 'abohm',
 'aboil',
 'abolish',
 'abolisher',
 'abolishment',
 'abolition',
 'abolitionary',
 'abolitionism',
 'abolitionist',
 'abolitionize',
 'abolla',
 'aboma',
 'abomasum',
 'abomasus',
 'abominable',
 'abominableness',
 'abominably',
 'abominate',
 'abomination',
 'abominator',
 'abomine',
 'Abongo',
 'aboon',
 'aborad',
 'aboral',
 'aborally',
 'abord',
 'aboriginal',
 'aboriginality',
 'aboriginally',
 'aboriginary',
 'aborigine',
 'abort',
 'aborted',
 'aborticide',
 'abortient',
 'abortifacient',
 'abortin',
 'abortion',
 'abortional',
 'abortionist',
 'abortive',
 'abortively',
 'abortiveness',
 'abortus',
 'abouchement',
 'abound',
 'abounder',
 'abounding',
 'aboundingly',
 'about',
 'abouts',
 'above',
 'aboveboard',
 'abovedeck',
 'aboveground',
 'aboveproof',
 'abovestairs',
 'abox',
 'abracadabra',
 'abrachia',
 'abradant',
 'abrade',
 'abrader',
 'Abraham',
 'Abrahamic',
 'Abrahamidae',
 'Abrahamite',
 'Abrahamitic',
 'abraid',
 'Abram',
 'Abramis',
 'abranchial',
 'abranchialism',
 'abranchian',
 'Abranchiata',
 'abranchiate',
 'abranchious',
 'abrasax',
 'abrase',
 'abrash',
 'abrasiometer',
 'abrasion',
 'abrasive',
 'abrastol',
 'abraum',
 'abraxas',
 'abreact',
 'abreaction',
 'abreast',
 'abrenounce',
 'abret',
 'abrico',
 'abridge',
 'abridgeable',
 'abridged',
 'abridgedly',
 'abridger',
 'abridgment',
 'abrim',
 'abrin',
 'abristle',
 'abroach',
 'abroad',
 'Abrocoma',
 'abrocome',
 'abrogable',
 'abrogate',
 'abrogation',
 'abrogative',
 'abrogator',
 'Abroma',
 'Abronia',
 'abrook',
 'abrotanum',
 'abrotine',
 'abrupt',
 'abruptedly',
 'abruption',
 'abruptly',
 'abruptness',
 'Abrus',
 'Absalom',
 'absampere',
 'Absaroka',
 'absarokite',
 'abscess',
 'abscessed',
 'abscession',
 'abscessroot',
 'abscind',
 'abscise',
 'abscision',
 'absciss',
 'abscissa',
 'abscissae',
 'abscisse',
 'abscission',
 'absconce',
 'abscond',
 'absconded',
 'abscondedly',
 'abscondence',
 'absconder',
 'absconsa',
 'abscoulomb',
 'absence',
 'absent',
 'absentation',
 'absentee',
 'absenteeism',
 'absenteeship',
 'absenter',
 'absently',
 'absentment',
 'absentmindedly',
 'absentness',
 'absfarad',
 'abshenry',
 'Absi',
 'absinthe',
 'absinthial',
 'absinthian',
 'absinthiate',
 'absinthic',
 'absinthin',
 'absinthine',
 'absinthism',
 'absinthismic',
 'absinthium',
 'absinthol',
 'absit',
 'absmho',
 'absohm',
 'absolute',
 'absolutely',
 'absoluteness',
 'absolution',
 'absolutism',
 'absolutist',
 'absolutistic',
 'absolutistically',
 'absolutive',
 'absolutization',
 'absolutize',
 'absolutory',
 'absolvable',
 'absolvatory',
 'absolve',
 'absolvent',
 'absolver',
 'absolvitor',
 'absolvitory',
 'absonant',
 'absonous',
 'absorb',
 'absorbability',
 'absorbable',
 'absorbed',
 'absorbedly',
 'absorbedness',
 'absorbefacient',
 'absorbency',
 'absorbent',
 'absorber',
 'absorbing',
 'absorbingly',
 'absorbition',
 'absorpt',
 'absorptance',
 'absorptiometer',
 'absorptiometric',
 'absorption',
 'absorptive',
 'absorptively',
 'absorptiveness',
 'absorptivity',
 'absquatulate',
 'abstain',
 'abstainer',
 'abstainment',
 'abstemious',
 'abstemiously',
 'abstemiousness',
 'abstention',
 'abstentionist',
 'abstentious',
 'absterge',
 'abstergent',
 'abstersion',
 'abstersive',
 'abstersiveness',
 'abstinence',
 'abstinency',
 'abstinent',
 'abstinential',
 'abstinently',
 'abstract',
 'abstracted',
 'abstractedly',
 'abstractedness',
 'abstracter',
 'abstraction',
 'abstractional',
 'abstractionism',
 'abstractionist',
 'abstractitious',
 'abstractive',
 'abstractively',
 'abstractiveness',
 'abstractly',
 'abstractness',
 'abstractor',
 'abstrahent',
 'abstricted',
 'abstriction',
 'abstruse',
 'abstrusely',
 'abstruseness',
 'abstrusion',
 'abstrusity',
 'absume',
 'absumption',
 'absurd',
 'absurdity',
 'absurdly',
 'absurdness',
 'absvolt',
 'Absyrtus',
 'abterminal',
 'abthain',
 'abthainrie',
 'abthainry',
 'abthanage',
 'Abu',
 'abu',
 'abucco',
 'abulia',
 'abulic',
 'abulomania',
 'abuna',
 'abundance',
 'abundancy',
 'abundant',
 'Abundantia',
 'abundantly',
 'abura',
 'aburabozu',
 'aburban',
 'aburst',
 'aburton',
 'abusable',
 'abuse',
 'abusedly',
 'abusee',
 'abuseful',
 'abusefully',
 'abusefulness',
 'abuser',
 'abusion',
 'abusious',
 'abusive',
 'abusively',
 'abusiveness',
 'abut',
 'Abuta',
 'Abutilon',
 'abutment',
 'abuttal',
 'abutter',
 'abutting',
 'abuzz',
 'abvolt',
 'abwab',
 'aby',
 'abysm',
 'abysmal',
 'abysmally',
 'abyss',
 'abyssal',
 'Abyssinian',
 'abyssobenthonic',
 'abyssolith',
 'abyssopelagic',
 'acacatechin',
 'acacatechol',
 'acacetin',
 'Acacia',
 'Acacian',
 'acaciin',
 'acacin',
 'academe',
 'academial',
 'academian',
 'Academic',
 'academic',
 'academical',
 'academically',
 'academicals',
 'academician',
 'academicism',
 'academism',
 'academist',
 'academite',
 'academization',
 'academize',
 'Academus',
 'academy',
 'Acadia',
 'acadialite',
 'Acadian',
 'Acadie',
 'Acaena',
 'acajou',
 'acaleph',
 'Acalepha',
 'Acalephae',
 'acalephan',
 'acalephoid',
 'acalycal',
 'acalycine',
 'acalycinous',
 'acalyculate',
 'Acalypha',
 'Acalypterae',
 'Acalyptrata',
 'Acalyptratae',
 'acalyptrate',
 'Acamar',
 'acampsia',
 'acana',
 'acanaceous',
 'acanonical',
 'acanth',
 'acantha',
 'Acanthaceae',
 'acanthaceous',
 'acanthad',
 'Acantharia',
 'Acanthia',
 'acanthial',
 'acanthin',
 'acanthine',
 'acanthion',
 'acanthite',
 'acanthocarpous',
 'Acanthocephala',
 'acanthocephalan',
 'Acanthocephali',
 'acanthocephalous',
 'Acanthocereus',
 'acanthocladous',
 'Acanthodea',
 'acanthodean',
 'Acanthodei',
 'Acanthodes',
 'acanthodian',
 'Acanthodidae',
 'Acanthodii',
 'Acanthodini',
 'acanthoid',
 'Acantholimon',
 'acanthological',
 'acanthology',
 'acantholysis',
 'acanthoma',
 'Acanthomeridae',
 'acanthon',
 'Acanthopanax',
 'Acanthophis',
 'acanthophorous',
 'acanthopod',
 'acanthopodous',
 'acanthopomatous',
 'acanthopore',
 'acanthopteran',
 'Acanthopteri',
 'acanthopterous',
 'acanthopterygian',
 'Acanthopterygii',
 'acanthosis',
 'acanthous',
 'Acanthuridae',
 'Acanthurus',
 'acanthus',
 'acapnia',
 'acapnial',
 'acapsular',
 'acapu',
 'acapulco',
 'acara',
 'Acarapis',
 'acardia',
 'acardiac',
 'acari',
 'acarian',
 'acariasis',
 'acaricidal',
 'acaricide',
 'acarid',
 'Acarida',
 'Acaridea',
 'acaridean',
 'acaridomatium',
 'acariform',
 'Acarina',
 'acarine',
 'acarinosis',
 'acarocecidium',
 'acarodermatitis',
 'acaroid',
 'acarol',
 'acarologist',
 'acarology',
 'acarophilous',
 'acarophobia',
 'acarotoxic',
 'acarpelous',
 'acarpous',
 'Acarus',
 'Acastus',
 'acatalectic',
 'acatalepsia',
 'acatalepsy',
 'acataleptic',
 'acatallactic',
 'acatamathesia',
 'acataphasia',
 'acataposis',
 'acatastasia',
 'acatastatic',
 'acate',
 'acategorical',
 'acatery',
 'acatharsia',
 'acatharsy',
 'acatholic',
 'acaudal',
 'acaudate',
 'acaulescent',
 'acauline',
 'acaulose',
 'acaulous',
 'acca',
 'accede',
 'accedence',
 'acceder',
 'accelerable',
 'accelerando',
 'accelerant',
 'accelerate',
 'accelerated',
 'acceleratedly',
 'acceleration',
 'accelerative',
 'accelerator',
 'acceleratory',
 'accelerograph',
 'accelerometer',
 'accend',
 'accendibility',
 'accendible',
 'accension',
 'accensor',
 'accent',
 'accentless',
 'accentor',
 'accentuable',
 'accentual',
 'accentuality',
 'accentually',
 'accentuate',
 'accentuation',
 'accentuator',
 'accentus',
 'accept',
 'acceptability',
 'acceptable',
 'acceptableness',
 'acceptably',
 'acceptance',
 'acceptancy',
 'acceptant',
 'acceptation',
 'accepted',
 'acceptedly',
 'accepter',
 'acceptilate',
 'acceptilation',
 'acception',
 'acceptive',
 'acceptor',
 'acceptress',
 'accerse',
 'accersition',
 'accersitor',
 'access',
 'accessarily',
 'accessariness',
 'accessary',
 'accessaryship',
 'accessibility',
 'accessible',
 'accessibly',
 'accession',
 'accessional',
 'accessioner',
 'accessive',
 'accessively',
 'accessless',
 'accessorial',
 'accessorily',
 'accessoriness',
 'accessorius',
 'accessory',
 'accidence',
 'accidency',
 'accident',
 'accidental',
 'accidentalism',
 'accidentalist',
 'accidentality',
 'accidentally',
 'accidentalness',
 'accidented',
 'accidential',
 'accidentiality',
 'accidently',
 'accidia',
 'accidie',
 'accinge',
 'accipient',
 'Accipiter',
 'accipitral',
 'accipitrary',
 'Accipitres',
 'accipitrine',
 'accismus',
 'accite',
 'acclaim',
 'acclaimable',
 'acclaimer',
 'acclamation',
 'acclamator',
 'acclamatory',
 'acclimatable',
 'acclimatation',
 'acclimate',
 'acclimatement',
 'acclimation',
 'acclimatizable',
 'acclimatization',
 'acclimatize',
 'acclimatizer',
 'acclimature',
 'acclinal',
 'acclinate',
 'acclivitous',
 'acclivity',
 'acclivous',
 'accloy',
 'accoast',
 'accoil',
 'accolade',
 'accoladed',
 'accolated',
 'accolent',
 'accolle',
 'accombination',
 'accommodable',
 'accommodableness',
 'accommodate',
 'accommodately',
 'accommodateness',
 'accommodating',
 'accommodatingly',
 'accommodation',
 'accommodational',
 'accommodative',
 'accommodativeness',
 'accommodator',
 'accompanier',
 'accompaniment',
 'accompanimental',
 'accompanist',
 'accompany',
 'accompanyist',
 'accompletive',
 'accomplice',
 'accompliceship',
 'accomplicity',
 'accomplish',
 'accomplishable',
 'accomplished',
 'accomplisher',
 'accomplishment',
 'accomplisht',
 'accompt',
 'accord',
 'accordable',
 'accordance',
 'accordancy',
 'accordant',
 ...]

In [73]:
words = pd.DataFrame(data=w, columns=['word'])
words

              word
0                A
1                a
2               aa
3              aal
4            aalii
...            ...
235881      zythem
235882      Zythia
235883      zythum
235884     Zyzomys
235885  Zyzzogeton

[235886 rows x 1 columns]

In [75]:
alice_words.merge(right=words, on=['word'], how='left', indicator=True).loc[lambda df_: df_['_merge'] == 'left_only']['word']

0              ﻿The
1           Project
2         Gutenberg
3             EBook
7        Wonderland
            ...
12741       Archive
12742    Foundation
12749        eBooks
12756         email
12762        eBooks
Name: word, Length: 2503, dtype: object

In [76]:
# 36.3

In [78]:
with open('data/alice-in-wonderland.txt', 'r') as f:
    data_new = f.read().split('\n\n')

In [79]:
data_new

['\ufeffThe Project Gutenberg EBook of Alice in Wonderland, by Lewis Carroll',
 'This eBook is for the use of anyone anywhere at no cost and with\nalmost no restrictions whatsoever.  You may copy it, give it away or\nre-use it under the terms of the Project Gutenberg License included\nwith this eBook or online at www.gutenberg.org',
 '\nTitle: Alice in Wonderland',
 'Author: Lewis Carroll',
 'Illustrator: Gordon Robinson',
 'Release Date: August 12, 2006 [EBook #19033]',
 'Language: English',
 '\n*** START OF THIS PROJECT GUTENBERG EBOOK ALICE IN WONDERLAND ***',
 '',
 '\nProduced by Jason Isbell, Irma Spehar, and the Online\nDistributed Proofreading Team at http://www.pgdp.net',
 '',
 '',
 '',
 '',
 '          [Illustration: Alice in the Room of the Duchess.]',
 '\n                       _THE "STORYLAND" SERIES_',
 '',
 "                   ALICE'S ADVENTURES IN WONDERLAND",
 '',
 '',
 '',
 "                     SAM'L GABRIEL SONS & COMPANY",
 '                               NEW YORK',
 '',
 '                           Copyright, 1916,',
 "                   by SAM'L GABRIEL SONS & COMPANY",
 '                               NEW YORK',
 '',
 "\nALICE'S ADVENTURES IN WONDERLAND",
 '[Illustration]',
 '',
 '\nI--DOWN THE RABBIT-HOLE',
 '\nAlice was beginning to get very tired of sitting by her sister on the\nbank, and of having nothing to do. Once or twice she had peeped into the\nbook her sister was reading, but it had no pictures or conversations in\nit, "and what is the use of a book," thought Alice, "without pictures or\nconversations?"',
 'So she was considering in her own mind (as well as she could, for the\nday made her feel very sleepy and stupid), whether the pleasure of\nmaking a daisy-chain would be worth the trouble of getting up and\npicking the daisies, when suddenly a White Rabbit with pink eyes ran\nclose by her.',
 'There was nothing so very remarkable in that, nor did Alice think it so\nvery much out of the way to hear the Rabbit say to itself, "Oh dear! Oh\ndear! I shall be too late!" But when the Rabbit actually took a watch\nout of its waistcoat-pocket and looked at it and then hurried on, Alice\nstarted to her feet, for it flashed across her mind that she had never\nbefore seen a rabbit with either a waistcoat-pocket, or a watch to take\nout of it, and, burning with curiosity, she ran across the field after\nit and was just in time to see it pop down a large rabbit-hole, under\nthe hedge. In another moment, down went Alice after it!',
 '[Illustration]',
 'The rabbit-hole went straight on like a tunnel for some way and then\ndipped suddenly down, so suddenly that Alice had not a moment to think\nabout stopping herself before she found herself falling down what seemed\nto be a very deep well.',
 'Either the well was very deep, or she fell very slowly, for she had\nplenty of time, as she went down, to look about her. First, she tried to\nmake out what she was coming to, but it was too dark to see anything;\nthen she looked at the sides of the well and noticed that they were\nfilled with cupboards and book-shelves; here and there she saw maps and\npictures hung upon pegs. She took down a jar from one of the shelves as\nshe passed. It was labeled "ORANGE MARMALADE," but, to her great\ndisappointment, it was empty; she did not like to drop the jar, so\nmanaged to put it into one of the cupboards as she fell past it.',
 'Down, down, down! Would the fall never come to an end? There was nothing\nelse to do, so Alice soon began talking to herself. "Dinah\'ll miss me\nvery much to-night, I should think!" (Dinah was the cat.) "I hope\nthey\'ll remember her saucer of milk at tea-time. Dinah, my dear, I wish\nyou were down here with me!" Alice felt that she was dozing off, when\nsuddenly, thump! thump! down she came upon a heap of sticks and dry\nleaves, and the fall was over.',
 'Alice was not a bit hurt, and she jumped up in a moment. She looked up,\nbut it was all dark overhead; before her was another long passage and\nthe White Rabbit was still in sight, hurrying down it. There was not a\nmoment to be lost. Away went Alice like the wind and was just in time to\nhear it say, as it turned a corner, "Oh, my ears and whiskers, how late\nit\'s getting!" She was close behind it when she turned the corner, but\nthe Rabbit was no longer to be seen.',
 "She found herself in a long, low hall, which was lit up by a row of\nlamps hanging from the roof. There were doors all 'round the hall, but\nthey were all locked; and when Alice had been all the way down one side\nand up the other, trying every door, she walked sadly down the middle,\nwondering how she was ever to get out again.",
 "Suddenly she came upon a little table, all made of solid glass. There\nwas nothing on it but a tiny golden key, and Alice's first idea was that\nthis might belong to one of the doors of the hall; but, alas! either the\nlocks were too large, or the key was too small, but, at any rate, it\nwould not open any of them. However, on the second time 'round, she came\nupon a low curtain she had not noticed before, and behind it was a\nlittle door about fifteen inches high. She tried the little golden key\nin the lock, and to her great delight, it fitted!",
 '[Illustration]',
 'Alice opened the door and found that it led into a small passage, not\nmuch larger than a rat-hole; she knelt down and looked along the passage\ninto the loveliest garden you ever saw. How she longed to get out of\nthat dark hall and wander about among those beds of bright flowers and\nthose cool fountains, but she could not even get her head through the\ndoorway. "Oh," said Alice, "how I wish I could shut up like a telescope!\nI think I could, if I only knew how to begin."',
 'Alice went back to the table, half hoping she might find another key on\nit, or at any rate, a book of rules for shutting people up like\ntelescopes. This time she found a little bottle on it ("which certainly\nwas not here before," said Alice), and tied \'round the neck of the\nbottle was a paper label, with the words "DRINK ME" beautifully printed\non it in large letters.',
 '"No, I\'ll look first," she said, "and see whether it\'s marked \'_poison_\'\nor not," for she had never forgotten that, if you drink from a bottle\nmarked "poison," it is almost certain to disagree with you, sooner or\nlater. However, this bottle was _not_ marked "poison," so Alice ventured\nto taste it, and, finding it very nice (it had a sort of mixed flavor of\ncherry-tart, custard, pineapple, roast turkey, toffy and hot buttered\ntoast), she very soon finished it off.',
 '       *       *       *       *       *',
 '"What a curious feeling!" said Alice. "I must be shutting up like a\ntelescope!"',
 'And so it was indeed! She was now only ten inches high, and her face\nbrightened up at the thought that she was now the right size for going\nthrough the little door into that lovely garden.',
 'After awhile, finding that nothing more happened, she decided on going\ninto the garden at once; but, alas for poor Alice! When she got to the\ndoor, she found she had forgotten the little golden key, and when she\nwent back to the table for it, she found she could not possibly reach\nit: she could see it quite plainly through the glass and she tried her\nbest to climb up one of the legs of the table, but it was too slippery,\nand when she had tired herself out with trying, the poor little thing\nsat down and cried.',
 '"Come, there\'s no use in crying like that!" said Alice to herself rather\nsharply. "I advise you to leave off this minute!" She generally gave\nherself very good advice (though she very seldom followed it), and\nsometimes she scolded herself so severely as to bring tears into her\neyes.',
 'Soon her eye fell on a little glass box that was lying under the table:\nshe opened it and found in it a very small cake, on which the words "EAT\nME" were beautifully marked in currants. "Well, I\'ll eat it," said\nAlice, "and if it makes me grow larger, I can reach the key; and if it\nmakes me grow smaller, I can creep under the door: so either way I\'ll\nget into the garden, and I don\'t care which happens!"',
 'She ate a little bit and said anxiously to herself, "Which way? Which\nway?" holding her hand on the top of her head to feel which way she was\ngrowing; and she was quite surprised to find that she remained the same\nsize. So she set to work and very soon finished off the cake.',
 '[Illustration]',
 '',
 '\nII--THE POOL OF TEARS',
 '\n"Curiouser and curiouser!" cried Alice (she was so much surprised that\nfor the moment she quite forgot how to speak good English). "Now I\'m\nopening out like the largest telescope that ever was! Good-by, feet! Oh,\nmy poor little feet, I wonder who will put on your shoes and stockings\nfor you now, dears? I shall be a great deal too far off to trouble\nmyself about you."',
 'Just at this moment her head struck against the roof of the hall; in\nfact, she was now rather more than nine feet high, and she at once took\nup the little golden key and hurried off to the garden door.',
 'Poor Alice! It was as much as she could do, lying down on one side, to\nlook through into the garden with one eye; but to get through was more\nhopeless than ever. She sat down and began to cry again.',
 "She went on shedding gallons of tears, until there was a large pool all\n'round her and reaching half down the hall.",
 'After a time, she heard a little pattering of feet in the distance and\nshe hastily dried her eyes to see what was coming. It was the White\nRabbit returning, splendidly dressed, with a pair of white kid-gloves in\none hand and a large fan in the other. He came trotting along in a\ngreat hurry, muttering to himself, "Oh! the Duchess, the Duchess! Oh!\n_won\'t_ she be savage if I\'ve kept her waiting!"',
 'When the Rabbit came near her, Alice began, in a low, timid voice, "If\nyou please, sir--" The Rabbit started violently, dropped the white\nkid-gloves and the fan and skurried away into the darkness as hard as he\ncould go.',
 '[Illustration]',
 'Alice took up the fan and gloves and she kept fanning herself all the\ntime she went on talking. "Dear, dear! How queer everything is to-day!\nAnd yesterday things went on just as usual. _Was_ I the same when I got\nup this morning? But if I\'m not the same, the next question is, \'Who in\nthe world am I?\' Ah, _that\'s_ the great puzzle!"',
 'As she said this, she looked down at her hands and was surprised to see\nthat she had put on one of the Rabbit\'s little white kid-gloves while\nshe was talking. "How _can_ I have done that?" she thought. "I must be\ngrowing small again." She got up and went to the table to measure\nherself by it and found that she was now about two feet high and was\ngoing on shrinking rapidly. She soon found out that the cause of this\nwas the fan she was holding and she dropped it hastily, just in time to\nsave herself from shrinking away altogether.',
 '"That _was_ a narrow escape!" said Alice, a good deal frightened at the\nsudden change, but very glad to find herself still in existence. "And\nnow for the garden!" And she ran with all speed back to the little door;\nbut, alas! the little door was shut again and the little golden key was\nlying on the glass table as before. "Things are worse than ever,"\nthought the poor child, "for I never was so small as this before,\nnever!"',
 'As she said these words, her foot slipped, and in another moment,\nsplash! she was up to her chin in salt-water. Her first idea was that\nshe had somehow fallen into the sea. However, she soon made out that she\nwas in the pool of tears which she had wept when she was nine feet high.',
 '[Illustration]',
 'Just then she heard something splashing about in the pool a little way\noff, and she swam nearer to see what it was: she soon made out that it\nwas only a mouse that had slipped in like herself.',
 '"Would it be of any use, now," thought Alice, "to speak to this mouse?\nEverything is so out-of-the-way down here that I should think very\nlikely it can talk; at any rate, there\'s no harm in trying." So she\nbegan, "O Mouse, do you know the way out of this pool? I am very tired\nof swimming about here, O Mouse!" The Mouse looked at her rather\ninquisitively and seemed to her to wink with one of its little eyes, but\nit said nothing.',
 '"Perhaps it doesn\'t understand English," thought Alice. "I dare say it\'s\na French mouse, come over with William the Conqueror." So she began\nagain: "Où est ma chatte?" which was the first sentence in her French\nlesson-book. The Mouse gave a sudden leap out of the water and seemed to\nquiver all over with fright. "Oh, I beg your pardon!" cried Alice\nhastily, afraid that she had hurt the poor animal\'s feelings. "I quite\nforgot you didn\'t like cats."',
 '"Not like cats!" cried the Mouse in a shrill, passionate voice. "Would\n_you_ like cats, if you were me?"',
 '"Well, perhaps not," said Alice in a soothing tone; "don\'t be angry\nabout it. And yet I wish I could show you our cat Dinah. I think you\'d\ntake a fancy to cats, if you could only see her. She is such a dear,\nquiet thing." The Mouse was bristling all over and she felt certain it\nmust be really offended. "We won\'t talk about her any more, if you\'d\nrather not."',
 '"We, indeed!" cried the Mouse, who was trembling down to the end of its\ntail. "As if _I_ would talk on such a subject! Our family always _hated_\ncats--nasty, low, vulgar things! Don\'t let me hear the name again!"',
 '[Illustration: Alice at the Mad Tea Party.]',
 '"I won\'t indeed!" said Alice, in a great hurry to change the subject of\nconversation. "Are you--are you fond--of--of dogs? There is such a nice\nlittle dog near our house, I should like to show you! It kills all the\nrats and--oh, dear!" cried Alice in a sorrowful tone. "I\'m afraid I\'ve\noffended it again!" For the Mouse was swimming away from her as hard as\nit could go, and making quite a commotion in the pool as it went.',
 'So she called softly after it, "Mouse dear! Do come back again, and we\nwon\'t talk about cats, or dogs either, if you don\'t like them!" When the\nMouse heard this, it turned \'round and swam slowly back to her; its face\nwas quite pale, and it said, in a low, trembling voice, "Let us get to\nthe shore and then I\'ll tell you my history and you\'ll understand why it\nis I hate cats and dogs."',
 'It was high time to go, for the pool was getting quite crowded with the\nbirds and animals that had fallen into it; there were a Duck and a Dodo,\na Lory and an Eaglet, and several other curious creatures. Alice led the\nway and the whole party swam to the shore.',
 '[Illustration]',
 '',
 '\nIII--A CAUCUS-RACE AND A LONG TALE',
 '\nThey were indeed a queer-looking party that assembled on the bank--the\nbirds with draggled feathers, the animals with their fur clinging close\nto them, and all dripping wet, cross and uncomfortable.',
 '[Illustration]',
 'The first question, of course, was how to get dry again. They had a\nconsultation about this and after a few minutes, it seemed quite natural\nto Alice to find herself talking familiarly with them, as if she had\nknown them all her life.',
 'At last the Mouse, who seemed to be a person of some authority among\nthem, called out, "Sit down, all of you, and listen to me! _I\'ll_ soon\nmake you dry enough!" They all sat down at once, in a large ring, with\nthe Mouse in the middle.',
 '"Ahem!" said the Mouse with an important air. "Are you all ready? This\nis the driest thing I know. Silence all \'round, if you please! \'William\nthe Conqueror, whose cause was favored by the pope, was soon submitted\nto by the English, who wanted leaders, and had been of late much\naccustomed to usurpation and conquest. Edwin and Morcar, the Earls of\nMercia and Northumbria\'--"',
 '"Ugh!" said the Lory, with a shiver.',
 '"--\'And even Stigand, the patriotic archbishop of Canterbury, found it\nadvisable\'--"',
 '"Found _what_?" said the Duck.',
 '"Found _it_," the Mouse replied rather crossly; "of course, you know\nwhat \'it\' means."',
 '"I know what \'it\' means well enough, when _I_ find a thing," said the\nDuck; "it\'s generally a frog or a worm. The question is, what did the\narchbishop find?"',
 'The Mouse did not notice this question, but hurriedly went on, "\'--found\nit advisable to go with Edgar Atheling to meet William and offer him the\ncrown.\'--How are you getting on now, my dear?" it continued, turning to\nAlice as it spoke.',
 '"As wet as ever," said Alice in a melancholy tone; "it doesn\'t seem to\ndry me at all."',
 '"In that case," said the Dodo solemnly, rising to its feet, "I move that\nthe meeting adjourn, for the immediate adoption of more energetic\nremedies--"',
 '"Speak English!" said the Eaglet. "I don\'t know the meaning of half\nthose long words, and, what\'s more, I don\'t believe you do either!"',
 '"What I was going to say," said the Dodo in an offended tone, "is that\nthe best thing to get us dry would be a Caucus-race."',
 '"What _is_ a Caucus-race?" said Alice.',
 '[Illustration]',
 '"Why," said the Dodo, "the best way to explain it is to do it." First it\nmarked out a race-course, in a sort of circle, and then all the party\nwere placed along the course, here and there. There was no "One, two,\nthree and away!" but they began running when they liked and left off\nwhen they liked, so that it was not easy to know when the race was over.\nHowever, when they had been running half an hour or so and were quite\ndry again, the Dodo suddenly called out, "The race is over!" and they\nall crowded \'round it, panting and asking, "But who has won?"',
 'This question the Dodo could not answer without a great deal of thought.\nAt last it said, "_Everybody_ has won, and _all_ must have prizes."',
 '"But who is to give the prizes?" quite a chorus of voices asked.',
 '"Why, _she_, of course," said the Dodo, pointing to Alice with one\nfinger; and the whole party at once crowded \'round her, calling out, in\na confused way, "Prizes! Prizes!"',
 "Alice had no idea what to do, and in despair she put her hand into her\npocket and pulled out a box of comfits (luckily the salt-water had not\ngot into it) and handed them 'round as prizes. There was exactly one\na-piece, all 'round.",
 'The next thing was to eat the comfits; this caused some noise and\nconfusion, as the large birds complained that they could not taste\ntheirs, and the small ones choked and had to be patted on the back.\nHowever, it was over at last and they sat down again in a ring and\nbegged the Mouse to tell them something more.',
 '"You promised to tell me your history, you know," said Alice, "and why\nit is you hate--C and D," she added in a whisper, half afraid that it\nwould be offended again.',
 '"Mine is a long and a sad tale!" said the Mouse, turning to Alice and\nsighing.',
 '"It _is_ a long tail, certainly," said Alice, looking down with wonder\nat the Mouse\'s tail, "but why do you call it sad?" And she kept on\npuzzling about it while the Mouse was speaking, so that her idea of the\ntale was something like this:--',

In [80]:
s_new = pd.Series(data=data_new)
s_new

0      ﻿The Project Gutenberg EBook of Alice in Wonde...
1      This eBook is for the use of anyone anywhere a...
2                           \nTitle: Alice in Wonderland
3                                  Author: Lewis Carroll
4                           Illustrator: Gordon Robinson
                             ...
388    Professor Michael S. Hart is the originator of...
389    \nProject Gutenberg-tm eBooks are often create...
390    \nMost people start at our Web site which has ...
391                             http://www.gutenberg.org
392    This Web site includes information about Proje...
Length: 393, dtype: object

In [85]:
s_new.str.split().str.len().loc[lambda x: x > 0].describe()

count    369.000000
mean      34.588076
std       32.356262
min        1.000000
25%        9.000000
50%       24.000000
75%       52.000000
max      169.000000
dtype: float64