In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data/nyc_taxi_2019-01.csv', usecols=['passenger_count', 'trip_distance', 'payment_type', 'total_amount'])
df

         passenger_count  trip_distance  payment_type  total_amount
0                      1           1.50             1          9.95
1                      1           2.60             1         16.30
2                      3           0.00             1          5.80
3                      5           0.00             2          7.55
4                      5           0.00             2         55.55
...                  ...            ...           ...           ...
7667787                1           4.79             1         23.16
7667788                1           0.00             1          0.00
7667789                1           0.00             1          0.00
7667790                1           0.00             1          0.00
7667791                1           0.00             1          0.00

[7667792 rows x 4 columns]

In [5]:
len(df.loc[df['passenger_count'] > 8])

9

In [6]:
len(df.loc[df['passenger_count'] == 0])

117381

In [7]:
df.loc[df['passenger_count'].isnull()]

Empty DataFrame
Columns: [passenger_count, trip_distance, payment_type, total_amount]
Index: []

In [9]:
len(df.loc[(df['payment_type'] == 2) & (df['total_amount'] > 1000)])

5

In [11]:
len(df.loc[df['total_amount'] < 0])

7131

In [14]:
len(df.query('(trip_distance < trip_distance.mean()) & (total_amount > total_amount.mean())'))

411255

In [15]:
# 15.1

In [17]:
len(df.query('passenger_count > 8'))

9

In [18]:
# 15.2

In [20]:
len(df.query('(total_amount < 0) & (payment_type.isin([4, 6]))'))

2666

In [21]:
# 15.3

In [22]:
payments = df.groupby('payment_type')

In [24]:
cnt = payments['passenger_count'].count()

In [37]:
cnt_share = cnt / payments['passenger_count'].count().sum() * 100

In [28]:
amt = payments['total_amount'].sum()

In [38]:
amt_share = amt / payments['total_amount'].sum().sum() * 100

In [41]:
cnt_share.name = 'passenger_count_share'

In [33]:
amt.name

'total_amount'

In [42]:
amt_share.name = 'total_amount_share'

In [45]:
df1 = pd.concat(objs=[cnt, cnt_share, amt, amt_share], axis=1)
df1.loc[[1, 2], ['passenger_count_share', 'total_amount_share']].round(1)

              passenger_count_share  total_amount_share
payment_type
1                              71.5                76.4
2                              27.9                22.7

In [49]:
(df['payment_type'].value_counts(normalize=True) * 100).round(1).loc[[1, 2]]

payment_type
1    71.5
2    27.9
Name: proportion, dtype: float64