In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(
    'data/nyc-parking-violations-2020.csv',
    usecols=['Plate ID', 'Registration State', 'Vehicle Make', 'Vehicle Color', 'Street Name']
)
df

,Plate ID,Registration State,Vehicle Make,Street Name,Vehicle Color
0,J58JKX,NJ,HONDA,43 ST,BK
1,KRE6058,PA,ME/BE,UNION ST,BLK
2,444326R,NJ,LEXUS,CLERMONT AVENUE,BLACK
3,F728330,OH,CHEVR,DIVISION AVE,NaN
4,FMY9090,NY,JEEP,GRAND ST,GREY
...,...,...,...,...,...
12495729,62161MM,NY,FORD,3RD AVE,BR
12495730,GYE7330,NY,HONDA,PELHAM PARK DR,BLK
12495731,HNY4802,NY,FORD,LYDIG AVE,GY
12495732,T687081C,NY,TOYOT,E 68 STREET,BLK
12495733,3497ZN,WA,UTILI,W/S/O 182 STREET,WHITE

In [3]:
df['Vehicle Color'].nunique()

1896

In [5]:
df['Vehicle Color'].value_counts().head(30)

Vehicle Color
WH       2344858
GY       2307704
BK       2066374
WHITE    1061234
BL        775124
RD        483298
BLACK     465110
GREY      306787
BROWN     292348
SILVE     191477
GR        182929
BLUE      178298
RED       161693
TN        120576
BR        102204
YW         98700
BLK        91539
OTHER      60245
GREEN      58765
GL         54851
GRY        46527
MR         42812
GRAY       40854
WHT        35433
YELLO      32792
WHI        29760
OR         28100
BK.        27830
WT         25583
WT.        24593
Name: count, dtype: int64

In [6]:
colors_dict = {
    'WH': 'WHITE',
    'WHI': 'WHITE',
    'WT': 'WHITE',
    'WT.': 'WHITE',
    'WHT': 'WHITE',
    'GR': 'GRAY',
    'GY': 'GRAY',
    'GR': 'GRAY',
    'GRY': 'GRAY',
    'GREY': 'GRAY',
    'BK': 'BLACK',
    'BLK': 'BLACK',
    'BK.': 'BLACK',
    'BL': 'BLACK',
}

In [9]:
df['Vehicle Color'] = df['Vehicle Color'].replace(colors_dict)

In [10]:
df['Vehicle Color'].nunique()

1883

In [11]:
df['Vehicle Color'].value_counts().head(50)

Vehicle Color
WHITE    3521461
BLACK    3425977
GRAY     2884801
RD        483298
BROWN     292348
SILVE     191477
BLUE      178298
RED       161693
TN        120576
BR        102204
YW         98700
OTHER      60245
GREEN      58765
GL         54851
MR         42812
YELLO      32792
OR         28100
GY.        22460
GOLD       21687
TAN        21091
SIL        20116
BLU        15240
SL.        13145
LTGY       13055
ORANG      11506
SL         10343
LTG        10093
BL.         9649
LT/         8976
PR          7518
DK/         7498
W           7367
RD.         7128
DKGY        6004
GYGY        5039
BLK.        4853
GRN         4829
B           4145
WH.         3811
BRO         3802
DKG         3702
PURPL       3635
BRN         3582
BKGY        3504
WHBL        3489
DKBL        2912
GN          2883
WHT.        2796
BN          2787
BLUE.       2638
Name: count, dtype: int64

In [12]:
# 28.1

In [13]:
df['Vehicle Make'].value_counts()

Vehicle Make
TOYOT    1395273
HONDA    1343265
FORD     1328063
NISSA    1119587
CHEVR     711464
          ...
BEAVE          1
NELSO          1
HOWBY          1
BONEE          1
KIA (          1
Name: count, Length: 5210, dtype: int64

In [14]:
df['Vehicle Make'].unique()

array(['HONDA', 'ME/BE', 'LEXUS', ..., 'KASAK', 'Harle', 'KIA ('],
      shape=(5211,), dtype=object)

In [26]:
import string

def normalize_name(name):
    if not isinstance(name, str):
        return name

    new_name = ''

    for l in name.strip().upper():
        if l in string.ascii_uppercase:
            new_name += l

    return new_name

In [29]:
df['Vehicle Make'].apply(normalize_name).nunique()

4915

In [30]:
def normalize_name_v2(name):
    if not isinstance(name, str):
        return name

    new_name = []
    
    for l in name.strip().upper():
        if l.isalpha():
            new_name.append(l)

    return ''.join(new_name)

In [32]:
df['Vehicle Make'].apply(normalize_name_v2).nunique()

4915

In [36]:
df['Vehicle Make'].apply(lambda x: not isinstance(x, str)).sum()

np.int64(62420)

In [37]:
df[df['Vehicle Make'].apply(lambda x: not isinstance(x, str))]

,Plate ID,Registration State,Vehicle Make,Street Name,Vehicle Color
16,7533572,GV,NaN,E 58 ST,WHITE
45,CKHJ235,99,NaN,86 STREET,BLACK
48,60892MN,NY,NaN,E 23 ST,WHITE
69,XW155A,NJ,NaN,2ND AVE,WHITE
82,XFAH70,NJ,NaN,E 43,NaN
...,...,...,...,...,...
12495678,2434294,ME,NaN,GRAND AVE,WHITE
12495683,242778E,ME,NaN,GRINNELL PL,WHITE
12495692,60349JR,NY,NaN,W 48 ST,BLACK
12495709,2907941,IN,NaN,E 59TH ST,RED
12495715,TMT92K,NJ,NaN,W/S TILLOTSON AVE,WHITE

In [38]:
# 28.2

In [39]:
df['Street Name']

0                      43 ST
1                   UNION ST
2            CLERMONT AVENUE
3               DIVISION AVE
4                   GRAND ST
                  ...
12495729             3RD AVE
12495730      PELHAM PARK DR
12495731           LYDIG AVE
12495732         E 68 STREET
12495733    W/S/O 182 STREET
Name: Street Name, Length: 12495734, dtype: object

In [40]:
# 28.3

In [41]:
df['Registration State'].value_counts()

Registration State
NY    9753643
NJ    1096110
PA     338779
FL     174056
CT     165205
       ...
PE         18
SK          8
MX          7
NT          3
YT          2
Name: count, Length: 68, dtype: int64