In [1]:
import sqlite3
import numpy as np
import pandas as pd

In [11]:
db_connection = sqlite3.connect('first_test.db')

In [12]:
df = pd.read_sql('''select * from test limit 10;''', db_connection)
df

   id    num
0   1  100.0
1   2  200.0
2   3  300.0
3   4  400.0
4   5    NaN

In [13]:
cursor = db_connection.cursor()

In [28]:
cursor.execute('select * from test')

In [18]:
for row in cursor:
    print(row)

(1, 100)
(2, 200)
(3, 300)
(4, 400)
(5, None)

In [26]:
cursor.fetchone()

In [29]:
cursor.fetchall()

[(1, 100), (2, 200), (3, 300), (4, 400), (5, None)]

In [30]:
db_connection.close()

In [31]:
df.dtypes

id       int64
num    float64
dtype: object

In [32]:
df.describe()

             id         num
count  5.000000    4.000000
mean   3.000000  250.000000
std    1.581139  129.099445
min    1.000000  100.000000
25%    2.000000  175.000000
50%    3.000000  250.000000
75%    4.000000  325.000000
max    5.000000  400.000000