In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('fortune1000.csv')
df

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
1,Exxon Mobil,244363.0,19710.0,71200,Energy,Petroleum Refining
2,Berkshire Hathaway,242137.0,44940.0,377000,Financials,Insurance: Property and Casualty (Stock)
3,Apple,229234.0,48351.0,123000,Technology,"Computers, Office Equipment"
4,UnitedHealth Group,201159.0,10558.0,260000,Health Care,Health Care: Insurance and Managed Care
...,...,...,...,...,...,...
995,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers,Wholesalers: Diversified
996,Charles River Laboratories Intl,1858.0,123.4,11800,Health Care,Health Care: Pharmacy and Other Services
997,CoreLogic,1851.0,152.2,5900,Business Services,Financial Data Services
998,Ensign Group,1849.0,40.5,21301,Health Care,Health Care: Medical Facilities
999,HCP,1848.0,414.2,190,Financials,Real estate

In [3]:
df.nunique()

Company      1000
Revenues      951
Profits       971
Employees     754
Sector         21
Industry       74
dtype: int64

In [4]:
sectors = df.groupby(by=['Sector'])
sectors

In [6]:
sectors.get_group('Retailing')

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_1644/778600270.py:1: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sectors.get_group('Retailing')

,Company,Revenues,Profits,Employees,Sector,Industry
0,Walmart,500343.0,9862.0,2300000,Retailing,General Merchandisers
7,Amazon.com,177866.0,3033.0,566000,Retailing,Internet Services and Retailing
14,Costco,129025.0,2679.0,182000,Retailing,General Merchandisers
22,Home Depot,100904.0,8630.0,413000,Retailing,Specialty Retailers: Other
38,Target,71879.0,2934.0,345000,Retailing,General Merchandisers
...,...,...,...,...,...,...
909,99 Cents Only Stores,2194.0,-90.3,17200,Retailing,Specialty Retailers: Other
926,Express,2138.0,19.4,9576,Retailing,Specialty Retailers: Apparel
971,Finish Line,1934.0,-18.2,8200,Retailing,Specialty Retailers: Apparel
989,Barnes & Noble Education,1874.0,5.4,13375,Retailing,Specialty Retailers: Other
992,Childrens Place,1870.0,84.7,9800,Retailing,Specialty Retailers: Apparel

In [9]:
sectors.groups.keys()

dict_keys(['Aerospace & Defense', 'Apparel', 'Business Services', 'Chemicals', 'Energy', 'Engineering & Construction', 'Financials', 'Food &  Drug Stores', 'Food, Beverages & Tobacco', 'Health Care', 'Hotels, Restaurants & Leisure', 'Household Products', 'Industrials', 'Materials', 'Media', 'Motor Vehicles & Parts', 'Retailing', 'Technology', 'Telecommunications', 'Transportation', 'Wholesalers'])

In [10]:
len(sectors)

21

In [12]:
sectors.size()

Sector
Aerospace & Defense               25
Apparel                           14
Business Services                 53
Chemicals                         33
Energy                           107
Engineering & Construction        27
Financials                       155
Food &  Drug Stores               12
Food, Beverages & Tobacco         37
Health Care                       71
Hotels, Restaurants & Leisure     26
Household Products                28
Industrials                       49
Materials                         45
Media                             25
Motor Vehicles & Parts            19
Retailing                         77
Technology                       103
Telecommunications                10
Transportation                    40
Wholesalers                       44
dtype: int64

In [13]:
sectors.first()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Boeing,93392.0,8197.0,140800,Aerospace and Defense
Apparel,Nike,34350.0,4240.0,74400,Apparel
Business Services,ManpowerGroup,21034.0,545.4,29000,Temporary Help
Chemicals,DowDuPont,62683.0,1460.0,98000,Chemicals
Energy,Exxon Mobil,244363.0,19710.0,71200,Petroleum Refining
Engineering & Construction,Fluor,19521.0,191.4,56706,"Engineering, Construction"
Financials,Berkshire Hathaway,242137.0,44940.0,377000,Insurance: Property and Casualty (Stock)
Food & Drug Stores,Kroger,122662.0,1907.0,449000,Food and Drug Stores
"Food, Beverages & Tobacco",PepsiCo,63525.0,4857.0,263000,Food Consumer Products
Health Care,UnitedHealth Group,201159.0,10558.0,260000,Health Care: Insurance and Managed Care
"Hotels, Restaurants & Leisure",Marriott International,22894.0,1372.0,177000,"Hotels, Casinos, Resorts"
Household Products,Procter & Gamble,66217.0,15326.0,95000,Household and Personal Products
Industrials,General Electric,122274.0,-5786.0,313000,Industrial Machinery
Materials,International Paper,23302.0,2144.0,56000,"Packaging, Containers"
Media,Disney,55137.0,8980.0,199000,Entertainment
Motor Vehicles & Parts,General Motors,157311.0,-3864.0,180000,Motor Vehicles and Parts
Retailing,Walmart,500343.0,9862.0,2300000,General Merchandisers
Technology,Apple,229234.0,48351.0,123000,"Computers, Office Equipment"
Telecommunications,AT&T,160546.0,29450.0,254000,Telecommunications
Transportation,UPS,65872.0,4910.0,346415,"Mail, Package, and Freight Delivery"
Wholesalers,McKesson,198533.0,5070.0,64500,Wholesalers: Health Care

In [14]:
sectors.last()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,Aerojet Rocketdyne Holdings,1877.0,-9.2,5157,Aerospace and Defense
Apparel,Wolverine World Wide,2350.0,0.3,3700,Apparel
Business Services,CoreLogic,1851.0,152.2,5900,Financial Data Services
Chemicals,Stepan,1925.0,91.6,2096,Chemicals
Energy,Superior Energy Services,1874.0,-205.9,6400,"Oil and Gas Equipment, Services"
Engineering & Construction,TopBuild,1906.0,158.1,8400,"Engineering, Construction"
Financials,HCP,1848.0,414.2,190,Real estate
Food & Drug Stores,Freds,2064.0,-140.3,7324,Food and Drug Stores
"Food, Beverages & Tobacco",Universal,2071.0,106.3,24000,Tobacco
Health Care,Ensign Group,1849.0,40.5,21301,Health Care: Medical Facilities
"Hotels, Restaurants & Leisure",Vail Resorts,1907.0,210.6,20150,"Hotels, Casinos, Resorts"
Household Products,ACCO Brands,1949.0,131.7,6620,"Home Equipment, Furnishings"
Industrials,Rexnord,1918.0,74.1,8000,Industrial Machinery
Materials,Summit Materials,1933.0,121.8,6000,"Building Materials, Glass"
Media,Tribune Media,1867.0,194.1,6000,Entertainment
Motor Vehicles & Parts,Tower International,2066.0,47.6,7600,Motor Vehicles and Parts
Retailing,Childrens Place,1870.0,84.7,9800,Specialty Retailers: Apparel
Technology,VeriFone Systems,1871.0,-173.8,5600,Financial Data Services
Telecommunications,Zayo Group Holdings,2200.0,85.7,3794,Telecommunications
Transportation,Echo Global Logistics,1943.0,12.6,2453,Transportation and Logistics
Wholesalers,SiteOne Landscape Supply,1862.0,54.6,3664,Wholesalers: Diversified

In [15]:
sectors.nth(3)

,Company,Revenues,Profits,Employees,Sector,Industry
22,Home Depot,100904.0,8630.0,413000,Retailing,Specialty Retailers: Other
23,Bank of America Corp.,100264.0,18232.0,209376,Financials,Commercial Banks
28,Anthem,90040.0,3842.8,56000,Health Care,Health Care: Insurance and Managed Care
30,Valero Energy,88407.0,4065.0,10015,Energy,Petroleum Refining
33,IBM,79139.0,5753.0,397800,Technology,Information Technology Services
53,Sysco,55371.0,1142.5,66500,Wholesalers,Wholesalers: Food and Grocery
73,Charter Communications,41581.0,9895.0,94800,Telecommunications,Telecommunications
74,Delta Air Lines,41244.0,3577.0,86564,Transportation,Airlines
86,Coca-Cola,35410.0,1248.0,61800,"Food, Beverages & Tobacco",Beverages
87,Publix Super Markets,34837.0,2291.9,193000,Food & Drug Stores,Food and Drug Stores
96,3M,31657.0,4858.0,91536,Industrials,Miscellaneous
98,General Dynamics,30973.0,2912.0,98600,Aerospace & Defense,Aerospace and Defense
186,Goodyear Tire & Rubber,15377.0,346.0,64000,Motor Vehicles & Parts,Motor Vehicles and Parts
195,Newell Brands,14742.0,2748.8,49000,Household Products,"Home Equipment, Furnishings"
196,CBS,14710.0,357.0,14715,Media,Entertainment
198,Monsanto,14640.0,2260.0,21900,Chemicals,Chemicals
199,Aramark,14604.0,373.9,215000,Business Services,Diversified Outsourcing Services
226,Las Vegas Sands,12882.0,2806.0,50500,"Hotels, Restaurants & Leisure","Hotels, Casinos, Resorts"
229,Lennar,12646.0,810.5,9111,Engineering & Construction,Homebuilders
245,United States Steel,12250.0,387.0,29200,Materials,Metals
420,Ralph Lauren,6653.0,-99.3,18250,Apparel,Apparel

In [16]:
sectors.sum()

,Company,Revenues,Profits,Employees,Industry
Sector,,,,,
Aerospace & Defense,BoeingUnited TechnologiesLockheed MartinGenera...,383835.0,26733.5,1010124,Aerospace and DefenseAerospace and DefenseAero...
Apparel,NikeVFPVHRalph LaurenHanesbrandsUnder ArmourLe...,101157.3,6350.7,355699,ApparelApparelApparelApparelApparelApparelAppa...
Business Services,ManpowerGroupVisaOmnicom GroupAramarkWaste Man...,316090.0,37179.2,1593999,Temporary HelpFinancial Data ServicesAdvertisi...
Chemicals,DowDuPontSherwin-WilliamsPPG IndustriesMonsant...,251151.0,20475.0,474020,ChemicalsChemicalsChemicalsChemicalsChemicalsC...
Energy,Exxon MobilChevronPhillips 66Valero EnergyMara...,1543507.2,85369.6,981207,Petroleum RefiningPetroleum RefiningPetroleum ...
Engineering & Construction,FluorAECOMD.R. HortonLennarJacobs Engineering ...,172782.0,7121.0,420745,"Engineering, ConstructionEngineering, Construc..."
Financials,Berkshire HathawayJPMorgan ChaseFannie MaeBank...,2442480.0,264253.5,3500119,Insurance: Property and Casualty (Stock)Commer...
Food & Drug Stores,KrogerWalgreens Boots AllianceAlbertsons Cos.P...,405468.0,8440.3,1398074,Food and Drug StoresFood and Drug StoresFood a...
"Food, Beverages & Tobacco",PepsiCoArcher Daniels MidlandTyson FoodsCoca-C...,510232.0,54902.5,1079316,Food Consumer ProductsFood ProductionFood Prod...
Health Care,UnitedHealth GroupCVS HealthExpress Scripts Ho...,1507991.4,92791.1,2971189,Health Care: Insurance and Managed CareHealth ...
"Hotels, Restaurants & Leisure",Marriott InternationalMcDonaldsStarbucksLas Ve...,179825.0,21305.5,2304337,"Hotels, Casinos, ResortsFood ServicesFood Serv..."
Household Products,Procter & GambleKimberly-ClarkColgate-Palmoliv...,231779.8,27726.8,674896,Household and Personal ProductsHousehold and P...
Industrials,General ElectricCaterpillarHoneywell Internati...,520140.0,19114.3,1566110,Industrial MachineryConstruction and Farm Mach...
Materials,International PaperNucorWestRockUnited States ...,278298.0,13730.4,653751,"Packaging, ContainersMetalsPackaging, Containe..."
Media,DisneyTime WarnerTwenty-First Century FoxCBSVi...,230487.4,23019.9,545985,EntertainmentEntertainmentEntertainmentEnterta...
Motor Vehicles & Parts,General MotorsFord MotorLearGoodyear Tire & Ru...,433535.0,6861.1,943582,Motor Vehicles and PartsMotor Vehicles and Par...
Retailing,WalmartAmazon.comCostcoHome DepotTargetLowesBe...,1684353.0,55707.2,6800658,General MerchandisersInternet Services and Ret...
Technology,AppleAlphabetMicrosoftIBMDell TechnologiesInte...,1374822.3,177883.9,3196807,"Computers, Office EquipmentInternet Services a..."
Telecommunications,AT&TVerizonComcastCharter CommunicationsCentur...,466959.0,91965.8,785609,TelecommunicationsTelecommunicationsTelecommun...
Transportation,UPSFedExAmerican Airlines GroupDelta Air Lines...,455160.0,52960.3,1652113,"Mail, Package, and Freight DeliveryMail, Packa..."
Wholesalers,McKessonAmerisourceBergenCardinal HealthSyscoT...,888149.0,15657.4,744175,Wholesalers: Health CareWholesalers: Health Ca...

In [17]:
sectors.sum(numeric_only=True)

                                Revenues   Profits  Employees
Sector
Aerospace & Defense             383835.0   26733.5    1010124
Apparel                         101157.3    6350.7     355699
Business Services               316090.0   37179.2    1593999
Chemicals                       251151.0   20475.0     474020
Energy                         1543507.2   85369.6     981207
Engineering & Construction      172782.0    7121.0     420745
Financials                     2442480.0  264253.5    3500119
Food &  Drug Stores             405468.0    8440.3    1398074
Food, Beverages & Tobacco       510232.0   54902.5    1079316
Health Care                    1507991.4   92791.1    2971189
Hotels, Restaurants & Leisure   179825.0   21305.5    2304337
Household Products              231779.8   27726.8     674896
Industrials                     520140.0   19114.3    1566110
Materials                       278298.0   13730.4     653751
Media                           230487.4   23019.9     545985
Motor Vehicles & Parts          433535.0    6861.1     943582
Retailing                      1684353.0   55707.2    6800658
Technology                     1374822.3  177883.9    3196807
Telecommunications              466959.0   91965.8     785609
Transportation                  455160.0   52960.3    1652113
Wholesalers                     888149.0   15657.4     744175

In [18]:
sectors.max(numeric_only=True)

                               Revenues  Profits  Employees
Sector
Aerospace & Defense             93392.0   8197.0     204700
Apparel                         34350.0   4240.0      74400
Business Services               21034.0   6699.0     215000
Chemicals                       62683.0   3000.4      98000
Energy                         244363.0  19710.0      71200
Engineering & Construction      19521.0   1038.4      87000
Financials                     242137.0  44940.0     377000
Food &  Drug Stores            122662.0   4078.0     449000
Food, Beverages & Tobacco       63525.0  10999.0     263000
Health Care                    201159.0  21308.0     260000
Hotels, Restaurants & Leisure   22894.0   5192.3     450000
Household Products              66217.0  15326.0      95000
Industrials                    122274.0   4858.0     313000
Materials                       23302.0   2144.0      56000
Media                           55137.0   8980.0     199000
Motor Vehicles & Parts         157311.0   7602.0     202000
Retailing                      500343.0   9862.0    2300000
Technology                     229234.0  48351.0     397800
Telecommunications             160546.0  30101.0     254000
Transportation                  65872.0  10712.0     357000
Wholesalers                    198533.0   5070.0     113600

In [19]:
# Exercises

In [20]:
df = pd.read_csv('cereals.csv')
df

                         Name    Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran         Nabisco  Cold        70   10.0       6
1           100% Natural Bran     Quaker Oats  Cold       120    2.0       8
2                    All-Bran       Kellogg's  Cold        70    9.0       5
3   All-Bran with Extra Fiber       Kellogg's  Cold        50   14.0       0
4              Almond Delight  Ralston Purina  Cold       110    1.0       8
..                        ...             ...   ...       ...    ...     ...
72                    Triples   General Mills  Cold       110    0.0       3
73                       Trix   General Mills  Cold       110    0.0      12
74                 Wheat Chex  Ralston Purina  Cold       100    3.0       3
75                   Wheaties   General Mills  Cold       100    3.0       3
76        Wheaties Honey Gold   General Mills  Cold       110    1.0       8

[77 rows x 6 columns]

In [21]:
man = df.groupby(by=['Manufacturer'])

In [22]:
man.size()

Manufacturer
American Home Food Products     1
General Mills                  22
Kellogg's                      23
Nabisco                         6
Post                            9
Quaker Oats                     8
Ralston Purina                  8
dtype: int64

In [23]:
len(man)

7

In [25]:
man.get_group(('Nabisco',))

                         Name Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran      Nabisco  Cold        70   10.0       6
20     Cream of Wheat (Quick)      Nabisco   Hot       100    1.0       0
63             Shredded Wheat      Nabisco  Cold        80    3.0       0
64     Shredded Wheat 'n'Bran      Nabisco  Cold        90    4.0       0
65  Shredded Wheat spoon size      Nabisco  Cold        90    3.0       0
68    Strawberry Fruit Wheats      Nabisco  Cold        90    3.0       5

In [27]:
man.mean(numeric_only=True)

                               Calories     Fiber    Sugars
Manufacturer
American Home Food Products  100.000000  0.000000  3.000000
General Mills                111.363636  1.272727  7.954545
Kellogg's                    108.695652  2.739130  7.565217
Nabisco                       86.666667  4.000000  1.833333
Post                         108.888889  2.777778  8.777778
Quaker Oats                   95.000000  1.337500  5.250000
Ralston Purina               115.000000  1.875000  6.125000

In [29]:
man['Sugars'].max()

Manufacturer
American Home Food Products     3
General Mills                  14
Kellogg's                      15
Nabisco                         6
Post                           15
Quaker Oats                    12
Ralston Purina                 11
Name: Sugars, dtype: int64

In [30]:
man['Fiber'].min()

Manufacturer
American Home Food Products    0.0
General Mills                  0.0
Kellogg's                      0.0
Nabisco                        1.0
Post                           0.0
Quaker Oats                    0.0
Ralston Purina                 0.0
Name: Fiber, dtype: float64

In [33]:
def min_sugar(df):
    return df.nsmallest(1, columns=['Sugars'])

In [34]:
man.apply(min_sugar)

/var/folders/d6/q237b0c90bqfq_8yty4yh1v40000gn/T/ipykernel_1644/2570420392.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  man.apply(min_sugar)

,,Name,Manufacturer,Type,Calories,Fiber,Sugars
Manufacturer,,,,,,,
American Home Food Products,43,Maypo,American Home Food Products,Hot,100,0.0,3
General Mills,11,Cheerios,General Mills,Cold,110,2.0,1
Kellogg's,3,All-Bran with Extra Fiber,Kellogg's,Cold,50,14.0,0
Nabisco,20,Cream of Wheat (Quick),Nabisco,Hot,100,1.0,0
Post,33,Grape-Nuts,Post,Cold,110,3.0,3
Quaker Oats,57,Quaker Oatmeal,Quaker Oats,Hot,100,2.7,-1
Ralston Purina,61,Rice Chex,Ralston Purina,Cold,110,0.0,2