In [1]:
import numpy as np
import pandas as pd

In [20]:
nobel = pd.read_json('nobel.json')
nobel

                                                prizes
0    {'year': '2019', 'category': 'chemistry', 'lau...
1    {'year': '2019', 'category': 'economics', 'lau...
2    {'year': '2019', 'category': 'literature', 'la...
3    {'year': '2019', 'category': 'peace', 'laureat...
4    {'year': '2019', 'category': 'physics', 'overa...
..                                                 ...
641  {'year': '1901', 'category': 'chemistry', 'lau...
642  {'year': '1901', 'category': 'literature', 'la...
643  {'year': '1901', 'category': 'peace', 'laureat...
644  {'year': '1901', 'category': 'physics', 'laure...
645  {'year': '1901', 'category': 'medicine', 'laur...

[646 rows x 1 columns]

In [3]:
nobel.loc[2, 'prizes']

{'year': '2019',
 'category': 'literature',
 'laureates': [{'id': '980',
   'firstname': 'Peter',
   'surname': 'Handke',
   'motivation': '"for an influential work that with linguistic ingenuity has explored the periphery and the specificity of human experience"',
   'share': '1'}]}

In [4]:
nobel.loc[2]

prizes    {'year': '2019', 'category': 'literature', 'la...
Name: 2, dtype: object

In [5]:
chemistry_2019 = nobel.loc[0, 'prizes']

In [6]:
chemistry_2019

{'year': '2019',
 'category': 'chemistry',
 'laureates': [{'id': '976',
   'firstname': 'John',
   'surname': 'Goodenough',
   'motivation': '"for the development of lithium-ion batteries"',
   'share': '3'},
  {'id': '977',
   'firstname': 'M. Stanley',
   'surname': 'Whittingham',
   'motivation': '"for the development of lithium-ion batteries"',
   'share': '3'},
  {'id': '978',
   'firstname': 'Akira',
   'surname': 'Yoshino',
   'motivation': '"for the development of lithium-ion batteries"',
   'share': '3'}]}

In [7]:
pd.json_normalize(data=chemistry_2019)

   year   category                                          laureates
0  2019  chemistry  [{'id': '976', 'firstname': 'John', 'surname':...

In [8]:
pd.json_normalize(data=chemistry_2019, record_path='laureates')

,id,firstname,surname,motivation,share
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3

In [9]:
pd.json_normalize(data=chemistry_2019, record_path='laureates', meta=['year', 'category'])

,id,firstname,surname,motivation,share,year,category
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3,2019,chemistry
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3,2019,chemistry
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3,2019,chemistry

In [12]:
def add_laureates_key(entry):
    entry.setdefault('laureates', [])

In [22]:
nobel['prizes'].apply(add_laureates_key)

0      None
1      None
2      None
3      None
4      None
       ...
641    None
642    None
643    None
644    None
645    None
Name: prizes, Length: 646, dtype: object

In [23]:
pd.json_normalize(data=nobel['prizes'], record_path='laureates', meta=['year', 'category'])

,id,firstname,surname,motivation,share,year,category
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3,2019,chemistry
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3,2019,chemistry
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3,2019,chemistry
3,982,Abhijit,Banerjee,"""for their experimental approach to alleviatin...",3,2019,economics
4,983,Esther,Duflo,"""for their experimental approach to alleviatin...",3,2019,economics
...,...,...,...,...,...,...,...
945,569,Sully,Prudhomme,"""in special recognition of his poetic composit...",1,1901,literature
946,462,Henry,Dunant,"""for his humanitarian efforts to help wounded ...",2,1901,peace
947,463,Frédéric,Passy,"""for his lifelong work for international peace...",2,1901,peace
948,1,Wilhelm Conrad,Röntgen,"""in recognition of the extraordinary services ...",1,1901,physics
949,293,Emil,von Behring,"""for his work on serum therapy, especially its...",1,1901,medicine

In [24]:
winners = pd.json_normalize(data=nobel['prizes'], record_path='laureates', meta=['year', 'category'])

In [25]:
winners

,id,firstname,surname,motivation,share,year,category
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3,2019,chemistry
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3,2019,chemistry
2,978,Akira,Yoshino,"""for the development of lithium-ion batteries""",3,2019,chemistry
3,982,Abhijit,Banerjee,"""for their experimental approach to alleviatin...",3,2019,economics
4,983,Esther,Duflo,"""for their experimental approach to alleviatin...",3,2019,economics
...,...,...,...,...,...,...,...
945,569,Sully,Prudhomme,"""in special recognition of his poetic composit...",1,1901,literature
946,462,Henry,Dunant,"""for his humanitarian efforts to help wounded ...",2,1901,peace
947,463,Frédéric,Passy,"""for his lifelong work for international peace...",2,1901,peace
948,1,Wilhelm Conrad,Röntgen,"""in recognition of the extraordinary services ...",1,1901,physics
949,293,Emil,von Behring,"""for his work on serum therapy, especially its...",1,1901,medicine

In [27]:
winners.head(2).to_json(orient='records')

'[{"id":"976","firstname":"John","surname":"Goodenough","motivation":"\\"for the development of lithium-ion batteries\\"","share":"3","year":"2019","category":"chemistry"},{"id":"977","firstname":"M. Stanley","surname":"Whittingham","motivation":"\\"for the development of lithium-ion batteries\\"","share":"3","year":"2019","category":"chemistry"}]'

In [28]:
winners.head(2)

,id,firstname,surname,motivation,share,year,category
0,976,John,Goodenough,"""for the development of lithium-ion batteries""",3,2019,chemistry
1,977,M. Stanley,Whittingham,"""for the development of lithium-ion batteries""",3,2019,chemistry

In [29]:
winners.head(2).to_json(orient='split')

'{"columns":["id","firstname","surname","motivation","share","year","category"],"index":[0,1],"data":[["976","John","Goodenough","\\"for the development of lithium-ion batteries\\"","3","2019","chemistry"],["977","M. Stanley","Whittingham","\\"for the development of lithium-ion batteries\\"","3","2019","chemistry"]]}'

In [30]:
url = 'https://data.cityofnewyork.us/api/views/25th-nujf/rows.csv'

In [31]:
baby_names = pd.read_csv(url)

HTTPError: HTTP Error 403: Forbidden

In [3]:
pd.read_excel('Single Worksheet.xlsx')

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [4]:
pd.read_excel(io='Single Worksheet.xlsx', index_col='City', usecols=['City', 'First Name', 'Last Name'])

              First Name Last Name
City
Miami            Brandon     James
Denver              Sean   Hawkins
Los Angeles         Judy       Day
San Francisco     Ashley      Ruiz
Portland       Stephanie     Gomez

In [5]:
pd.read_excel(io='Multiple Worksheets.xlsx', sheet_name=0)

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [6]:
pd.read_excel(io='Multiple Worksheets.xlsx', sheet_name='Data 1')

  First Name Last Name           City Gender
0    Brandon     James          Miami      M
1       Sean   Hawkins         Denver      M
2       Judy       Day    Los Angeles      F
3     Ashley      Ruiz  San Francisco      F
4  Stephanie     Gomez       Portland      F

In [7]:
workbook = pd.read_excel(io='Multiple Worksheets.xlsx', sheet_name=None)

In [8]:
workbook

{'Data 1':   First Name Last Name           City Gender
 0    Brandon     James          Miami      M
 1       Sean   Hawkins         Denver      M
 2       Judy       Day    Los Angeles      F
 3     Ashley      Ruiz  San Francisco      F
 4  Stephanie     Gomez       Portland      F,
 'Data 2':   First Name Last Name           City Gender
 0     Parker     Power        Raleigh      F
 1    Preston  Prescott   Philadelphia      F
 2    Ronaldo   Donaldo         Bangor      M
 3      Megan   Stiller  San Francisco      M
 4     Bustin    Jieber         Austin      F,
 'Data 3':   First Name  Last Name     City Gender
 0     Robert     Miller  Seattle      M
 1       Tara     Garcia  Phoenix      F
 2    Raphael  Rodriguez  Orlando      M}

In [9]:
workbook['Data 2']

  First Name Last Name           City Gender
0     Parker     Power        Raleigh      F
1    Preston  Prescott   Philadelphia      F
2    Ronaldo   Donaldo         Bangor      M
3      Megan   Stiller  San Francisco      M
4     Bustin    Jieber         Austin      F

In [10]:
# Homework

In [15]:
df_json = pd.read_json('tv_shows.json')
df_json['shows'].loc[0]

{'show': 'The X-Files',
 'runtime': 60,
 'network': 'FOX',
 'episodes': [{'season': 1,
   'episode': 1,
   'name': 'Pilot',
   'air_date': '1993-09-11 01:00:00'},
  {'season': 1,
   'episode': 2,
   'name': 'Deep Throat',
   'air_date': '1993-09-18 01:00:00'},
  {'season': 1,
   'episode': 3,
   'name': 'Squeeze',
   'air_date': '1993-09-25 01:00:00'},
  {'season': 1,
   'episode': 4,
   'name': 'Conduit',
   'air_date': '1993-10-02 01:00:00'},
  {'season': 1,
   'episode': 5,
   'name': 'The Jersey Devil',
   'air_date': '1993-10-09 01:00:00'},
  {'season': 1,
   'episode': 6,
   'name': 'Shadows',
   'air_date': '1993-10-23 01:00:00'},
  {'season': 1,
   'episode': 7,
   'name': 'Ghost in the Machine',
   'air_date': '1993-10-30 01:00:00'},
  {'season': 1,
   'episode': 8,
   'name': 'Ice',
   'air_date': '1993-11-06 02:00:00'},
  {'season': 1,
   'episode': 9,
   'name': 'Space',
   'air_date': '1993-11-13 02:00:00'},
  {'season': 1,
   'episode': 10,
   'name': 'Fallen Angel',
   'air_date': '1993-11-20 02:00:00'},
  {'season': 1,
   'episode': 11,
   'name': 'Eve',
   'air_date': '1993-12-11 02:00:00'},
  {'season': 1,
   'episode': 12,
   'name': 'Fire',
   'air_date': '1993-12-18 02:00:00'},
  {'season': 1,
   'episode': 13,
   'name': 'Beyond the Sea',
   'air_date': '1994-01-08 02:00:00'},
  {'season': 1,
   'episode': 14,
   'name': 'Gender Bender',
   'air_date': '1994-01-22 02:00:00'},
  {'season': 1,
   'episode': 15,
   'name': 'Lazarus',
   'air_date': '1994-02-05 02:00:00'},
  {'season': 1,
   'episode': 16,
   'name': 'Young at Heart',
   'air_date': '1994-02-12 02:00:00'},
  {'season': 1,
   'episode': 17,
   'name': 'E.B.E.',
   'air_date': '1994-02-19 02:00:00'},
  {'season': 1,
   'episode': 18,
   'name': 'Miracle Man',
   'air_date': '1994-03-19 02:00:00'},
  {'season': 1,
   'episode': 19,
   'name': 'Shapes',
   'air_date': '1994-04-02 02:00:00'},
  {'season': 1,
   'episode': 20,
   'name': 'Darkness Falls',
   'air_date': '1994-04-16 01:00:00'},
  {'season': 1,
   'episode': 21,
   'name': 'Tooms',
   'air_date': '1994-04-23 01:00:00'},
  {'season': 1,
   'episode': 22,
   'name': 'Born Again',
   'air_date': '1994-04-30 01:00:00'},
  {'season': 1,
   'episode': 23,
   'name': 'Roland',
   'air_date': '1994-05-07 01:00:00'},
  {'season': 1,
   'episode': 24,
   'name': 'The Erlenmeyer Flask',
   'air_date': '1994-05-14 01:00:00'},
  {'season': 2,
   'episode': 1,
   'name': 'Little Green Men',
   'air_date': '1994-09-17 01:00:00'},
  {'season': 2,
   'episode': 2,
   'name': 'The Host',
   'air_date': '1994-09-24 01:00:00'},
  {'season': 2,
   'episode': 3,
   'name': 'Blood',
   'air_date': '1994-10-01 01:00:00'},
  {'season': 2,
   'episode': 4,
   'name': 'Sleepless',
   'air_date': '1994-10-08 01:00:00'},
  {'season': 2,
   'episode': 5,
   'name': 'Duane Barry (1)',
   'air_date': '1994-10-15 01:00:00'},
  {'season': 2,
   'episode': 6,
   'name': 'Ascension (2)',
   'air_date': '1994-10-22 01:00:00'},
  {'season': 2, 'episode': 7, 'name': '3', 'air_date': '1994-11-05 02:00:00'},
  {'season': 2,
   'episode': 8,
   'name': 'One Breath',
   'air_date': '1994-11-12 02:00:00'},
  {'season': 2,
   'episode': 9,
   'name': 'Firewalker',
   'air_date': '1994-11-19 02:00:00'},
  {'season': 2,
   'episode': 10,
   'name': 'Red Museum',
   'air_date': '1994-12-10 02:00:00'},
  {'season': 2,
   'episode': 11,
   'name': 'Excelsis Dei',
   'air_date': '1994-12-17 02:00:00'},
  {'season': 2,
   'episode': 12,
   'name': 'Aubrey',
   'air_date': '1995-01-07 02:00:00'},
  {'season': 2,
   'episode': 13,
   'name': 'Irresistible',
   'air_date': '1995-01-14 02:00:00'},
  {'season': 2,
   'episode': 14,
   'name': 'Die Hand die Verletzt',
   'air_date': '1995-01-28 02:00:00'},
  {'season': 2,
   'episode': 15,
   'name': 'Fresh Bones',
   'air_date': '1995-02-04 02:00:00'},
  {'season': 2,
   'episode': 16,
   'name': 'Colony (1)',
   'air_date': '1995-02-11 02:00:00'},
  {'season': 2,
   'episode': 17,
   'name': 'End Game (2)',
   'air_date': '1995-02-18 02:00:00'},
  {'season': 2,
   'episode': 18,
   'name': 'Fearful Symmetry',
   'air_date': '1995-02-25 02:00:00'},
  {'season': 2,
   'episode': 19,
   'name': 'Død Kalm',
   'air_date': '1995-03-11 02:00:00'},
  {'season': 2,
   'episode': 20,
   'name': 'Humbug',
   'air_date': '1995-04-01 02:00:00'},
  {'season': 2,
   'episode': 21,
   'name': 'The Calusari',
   'air_date': '1995-04-15 01:00:00'},
  {'season': 2,
   'episode': 22,
   'name': 'F. Emasculata',
   'air_date': '1995-04-29 01:00:00'},
  {'season': 2,
   'episode': 23,
   'name': 'Soft Light',
   'air_date': '1995-05-06 01:00:00'},
  {'season': 2,
   'episode': 24,
   'name': 'Our Town',
   'air_date': '1995-05-13 01:00:00'},
  {'season': 2,
   'episode': 25,
   'name': 'Anasazi',
   'air_date': '1995-05-20 01:00:00'},
  {'season': 3,
   'episode': 1,
   'name': 'The Blessing Way',
   'air_date': '1995-09-23 01:00:00'},
  {'season': 3,
   'episode': 2,
   'name': 'Paper Clip',
   'air_date': '1995-09-30 01:00:00'},
  {'season': 3,
   'episode': 3,
   'name': 'D.P.O.',
   'air_date': '1995-10-07 01:00:00'},
  {'season': 3,
   'episode': 4,
   'name': "Clyde Bruckman's Final Repose",
   'air_date': '1995-10-14 01:00:00'},
  {'season': 3,
   'episode': 5,
   'name': 'The List',
   'air_date': '1995-10-21 01:00:00'},
  {'season': 3,
   'episode': 6,
   'name': '2Shy',
   'air_date': '1995-11-04 02:00:00'},
  {'season': 3,
   'episode': 7,
   'name': 'The Walk',
   'air_date': '1995-11-11 02:00:00'},
  {'season': 3,
   'episode': 8,
   'name': 'Oubliette',
   'air_date': '1995-11-18 02:00:00'},
  {'season': 3,
   'episode': 9,
   'name': 'Nisei (1)',
   'air_date': '1995-11-25 02:00:00'},
  {'season': 3,
   'episode': 10,
   'name': '731 (2)',
   'air_date': '1995-12-02 02:00:00'},
  {'season': 3,
   'episode': 11,
   'name': 'Revelations',
   'air_date': '1995-12-16 02:00:00'},
  {'season': 3,
   'episode': 12,
   'name': 'War of the Coprophages',
   'air_date': '1996-01-06 02:00:00'},
  {'season': 3,
   'episode': 13,
   'name': 'Syzygy',
   'air_date': '1996-01-27 02:00:00'},
  {'season': 3,
   'episode': 14,
   'name': 'Grotesque',
   'air_date': '1996-02-03 02:00:00'},
  {'season': 3,
   'episode': 15,
   'name': 'Piper Maru (1)',
   'air_date': '1996-02-10 02:00:00'},
  {'season': 3,
   'episode': 16,
   'name': 'Apocrypha (2)',
   'air_date': '1996-02-17 02:00:00'},
  {'season': 3,
   'episode': 17,
   'name': 'Pusher',
   'air_date': '1996-02-24 02:00:00'},
  {'season': 3,
   'episode': 18,
   'name': 'Teso dos Bichos',
   'air_date': '1996-03-09 02:00:00'},
  {'season': 3,
   'episode': 19,
   'name': 'Hell Money',
   'air_date': '1996-03-30 02:00:00'},
  {'season': 3,
   'episode': 20,
   'name': "Jose Chung's 'From Outer Space'",
   'air_date': '1996-04-13 01:00:00'},
  {'season': 3,
   'episode': 21,
   'name': 'Avatar',
   'air_date': '1996-04-27 01:00:00'},
  {'season': 3,
   'episode': 22,
   'name': 'Quagmire',
   'air_date': '1996-05-04 01:00:00'},
  {'season': 3,
   'episode': 23,
   'name': 'Wetwired',
   'air_date': '1996-05-11 01:00:00'},
  {'season': 3,
   'episode': 24,
   'name': 'Talitha Cumi (1)',
   'air_date': '1996-05-18 01:00:00'},
  {'season': 4,
   'episode': 1,
   'name': 'Herrenvolk (2)',
   'air_date': '1996-10-05 01:00:00'},
  {'season': 4,
   'episode': 2,
   'name': 'Home',
   'air_date': '1996-10-12 01:00:00'},
  {'season': 4,
   'episode': 3,
   'name': 'Teliko',
   'air_date': '1996-10-19 01:00:00'},
  {'season': 4,
   'episode': 4,
   'name': 'Unruhe',
   'air_date': '1996-10-28 02:00:00'},
  {'season': 4,
   'episode': 5,
   'name': 'The Field Where I Died',
   'air_date': '1996-11-04 02:00:00'},
  {'season': 4,
   'episode': 6,
   'name': 'Sanguinarium',
   'air_date': '1996-11-11 02:00:00'},
  {'season': 4,
   'episode': 7,
   'name': 'Musings of a Cigarette-Smoking Man',
   'air_date': '1996-11-18 02:00:00'},
  {'season': 4,
   'episode': 8,
   'name': 'Tunguska (1)',
   'air_date': '1996-11-25 02:00:00'},
  {'season': 4,
   'episode': 9,
   'name': 'Terma (2)',
   'air_date': '1996-12-02 02:00:00'},
  {'season': 4,
   'episode': 10,
   'name': 'Paper Hearts',
   'air_date': '1996-12-16 02:00:00'},
  {'season': 4,
   'episode': 11,
   'name': 'El Mundo Gira',
   'air_date': '1997-01-13 02:00:00'},
  {'season': 4,
   'episode': 12,
   'name': 'Leonard Betts',
   'air_date': '1997-01-27 02:00:00'},
  {'season': 4,
   'episode': 13,
   'name': 'Never Again',
   'air_date': '1997-02-03 02:00:00'},
  {'season': 4,
   'episode': 14,
   'name': 'Memento Mori',
   'air_date': '1997-02-10 02:00:00'},
  {'season': 4,
   'episode': 15,
   'name': 'Kaddish',
   'air_date': '1997-02-17 02:00:00'},
  {'season': 4,
   'episode': 16,
   'name': 'Unrequited',
   'air_date': '1997-02-24 02:00:00'},
  {'season': 4,
   'episode': 17,
   'name': 'Tempus Fugit (1)',
   'air_date': '1997-03-17 02:00:00'},
  {'season': 4,
   'episode': 18,
   'name': 'Max (2)',
   'air_date': '1997-03-24 02:00:00'},
  {'season': 4,
   'episode': 19,
   'name': 'Synchrony',
   'air_date': '1997-04-14 01:00:00'},
  {'season': 4,
   'episode': 20,
   'name': 'Small Potatoes',
   'air_date': '1997-04-21 01:00:00'},
  {'season': 4,
   'episode': 21,
   'name': 'Zero Sum',
   'air_date': '1997-04-28 01:00:00'},
  {'season': 4,
   'episode': 22,
   'name': 'Elegy',
   'air_date': '1997-05-05 01:00:00'},
  {'season': 4,
   'episode': 23,
   'name': 'Demons',
   'air_date': '1997-05-12 01:00:00'},
  {'season': 4,
   'episode': 24,
   'name': 'Gethsemane',
   'air_date': '1997-05-19 01:00:00'},
  {'season': 5,
   'episode': 1,
   'name': 'Redux (1)',
   'air_date': '1997-11-03 02:00:00'},
  {'season': 5,
   'episode': 2,
   'name': 'Redux (2)',
   'air_date': '1997-11-10 02:00:00'},
  {'season': 5,
   'episode': 3,
   'name': 'Unusual Suspects',
   'air_date': '1997-11-17 02:00:00'},
  {'season': 5,
   'episode': 4,
   'name': 'Detour',
   'air_date': '1997-11-24 02:00:00'},
  {'season': 5,
   'episode': 5,
   'name': 'The Post-Modern Prometheus',
   'air_date': '1997-12-01 02:00:00'},
  {'season': 5,
   'episode': 6,
   'name': 'Christmas Carol (1)',
   'air_date': '1997-12-08 02:00:00'},
  {'season': 5,
   'episode': 7,
   'name': 'Emily (2)',
   'air_date': '1997-12-15 02:00:00'},
  {'season': 5,
   'episode': 8,
   'name': 'Kitsunegari',
   'air_date': '1998-01-05 02:00:00'},
  {'season': 5,
   'episode': 9,
   'name': 'Schizogeny',
   'air_date': '1998-01-12 02:00:00'},
  {'season': 5,
   'episode': 10,
   'name': 'Chinga',
   'air_date': '1998-02-09 02:00:00'},
  {'season': 5,
   'episode': 11,
   'name': 'Kill Switch',
   'air_date': '1998-02-16 02:00:00'},
  {'season': 5,
   'episode': 12,
   'name': 'Bad Blood',
   'air_date': '1998-02-23 02:00:00'},
  {'season': 5,
   'episode': 13,
   'name': 'Patient X (1)',
   'air_date': '1998-03-02 02:00:00'},
  {'season': 5,
   'episode': 14,
   'name': 'The Red and the Black (2)',
   'air_date': '1998-03-09 02:00:00'},
  {'season': 5,
   'episode': 15,
   'name': 'Travelers',
   'air_date': '1998-03-30 02:00:00'},
  {'season': 5,
   'episode': 16,
   'name': "Mind's Eye",
   'air_date': '1998-04-20 01:00:00'},
  {'season': 5,
   'episode': 17,
   'name': 'All Souls',
   'air_date': '1998-04-27 01:00:00'},
  {'season': 5,
   'episode': 18,
   'name': 'The Pine Bluff Variant',
   'air_date': '1998-05-04 01:00:00'},
  {'season': 5,
   'episode': 19,
   'name': 'Folie a Deux',
   'air_date': '1998-05-11 01:00:00'},
  {'season': 5,
   'episode': 20,
   'name': 'The End',
   'air_date': '1998-05-18 01:00:00'},
  {'season': 6,
   'episode': 1,
   'name': 'The Beginning',
   'air_date': '1998-11-09 02:00:00'},
  {'season': 6,
   'episode': 2,
   'name': 'Drive',
   'air_date': '1998-11-16 02:00:00'},
  {'season': 6,
   'episode': 3,
   'name': 'Triangle',
   'air_date': '1998-11-23 02:00:00'},
  {'season': 6,
   'episode': 4,
   'name': 'Dreamland (1)',
   'air_date': '1998-11-30 02:00:00'},
  {'season': 6,
   'episode': 5,
   'name': 'Dreamland (2)',
   'air_date': '1998-12-07 02:00:00'},
  {'season': 6,
   'episode': 6,
   'name': 'How the Ghosts Stole Christmas',
   'air_date': '1998-12-14 02:00:00'},
  {'season': 6,
   'episode': 7,
   'name': 'Terms of Endearment',
   'air_date': '1999-01-04 02:00:00'},
  {'season': 6,
   'episode': 8,
   'name': 'The Rain King',
   'air_date': '1999-01-11 02:00:00'},
  {'season': 6,
   'episode': 9,
   'name': 'S.R. 819',
   'air_date': '1999-01-18 02:00:00'},
  {'season': 6,
   'episode': 10,
   'name': 'Tithonus',
   'air_date': '1999-01-25 02:00:00'},
  {'season': 6,
   'episode': 11,
   'name': 'Two Fathers (1)',
   'air_date': '1999-02-08 02:00:00'},
  {'season': 6,
   'episode': 12,
   'name': 'One Son (2)',
   'air_date': '1999-02-15 02:00:00'},
  {'season': 6,
   'episode': 13,
   'name': 'Agua Mala',
   'air_date': '1999-02-22 02:00:00'},
  {'season': 6,
   'episode': 14,
   'name': 'Monday',
   'air_date': '1999-03-01 02:00:00'},
  {'season': 6,
   'episode': 15,
   'name': 'Arcadia',
   'air_date': '1999-03-08 02:00:00'},
  {'season': 6,
   'episode': 16,
   'name': 'Alpha',
   'air_date': '1999-03-29 02:00:00'},
  {'season': 6,
   'episode': 17,
   'name': 'Trevor',
   'air_date': '1999-04-12 01:00:00'},
  {'season': 6,
   'episode': 18,
   'name': 'Milagro',
   'air_date': '1999-04-19 01:00:00'},
  {'season': 6,
   'episode': 19,
   'name': 'The Unnatural',
   'air_date': '1999-04-26 01:00:00'},
  {'season': 6,
   'episode': 20,
   'name': 'Three of a Kind',
   'air_date': '1999-05-03 01:00:00'},
  {'season': 6,
   'episode': 21,
   'name': 'Field Trip',
   'air_date': '1999-05-10 01:00:00'},
  {'season': 6,
   'episode': 22,
   'name': 'Biogenesis',
   'air_date': '1999-05-17 01:00:00'},
  {'season': 7,
   'episode': 1,
   'name': 'The Sixth Extinction (1)',
   'air_date': '1999-11-08 02:00:00'},
  {'season': 7,
   'episode': 2,
   'name': 'The Sixth Extinction (2): Amor Fati',
   'air_date': '1999-11-15 02:00:00'},
  {'season': 7,
   'episode': 3,
   'name': 'Hungry',
   'air_date': '1999-11-22 02:00:00'},
  {'season': 7,
   'episode': 4,
   'name': 'Millennium',
   'air_date': '1999-11-29 02:00:00'},
  {'season': 7,
   'episode': 5,
   'name': 'Rush',
   'air_date': '1999-12-06 02:00:00'},
  {'season': 7,
   'episode': 6,
   'name': 'The Goldberg Variation',
   'air_date': '1999-12-13 02:00:00'},
  {'season': 7,
   'episode': 7,
   'name': 'Orison',
   'air_date': '2000-01-10 02:00:00'},
  {'season': 7,
   'episode': 8,
   'name': 'The Amazing Maleeni',
   'air_date': '2000-01-17 02:00:00'},
  {'season': 7,
   'episode': 9,
   'name': 'Signs and Wonders',
   'air_date': '2000-01-24 02:00:00'},
  {'season': 7,
   'episode': 10,
   'name': 'Sein und Zeit (1)',
   'air_date': '2000-02-07 02:00:00'},
  {'season': 7,
   'episode': 11,
   'name': 'Closure (2)',
   'air_date': '2000-02-14 02:00:00'},
  {'season': 7,
   'episode': 12,
   'name': 'X-Cops',
   'air_date': '2000-02-21 02:00:00'},
  {'season': 7,
   'episode': 13,
   'name': 'First Person Shooter',
   'air_date': '2000-02-28 02:00:00'},
  {'season': 7,
   'episode': 14,
   'name': 'Theef',
   'air_date': '2000-03-13 02:00:00'},
  {'season': 7,
   'episode': 15,
   'name': 'En Ami',
   'air_date': '2000-03-20 02:00:00'},
  {'season': 7,
   'episode': 16,
   'name': 'Chimera',
   'air_date': '2000-04-03 01:00:00'},
  {'season': 7,
   'episode': 17,
   'name': 'all things',
   'air_date': '2000-04-10 01:00:00'},
  {'season': 7,
   'episode': 18,
   'name': 'Brand X',
   'air_date': '2000-04-17 01:00:00'},
  {'season': 7,
   'episode': 19,
   'name': 'Hollywood A.D.',
   'air_date': '2000-05-01 01:00:00'},
  {'season': 7,
   'episode': 20,
   'name': 'Fight Club',
   'air_date': '2000-05-08 01:00:00'},
  {'season': 7,
   'episode': 21,
   'name': 'Je Souhaite',
   'air_date': '2000-05-15 01:00:00'},
  {'season': 7,
   'episode': 22,
   'name': 'Requiem',
   'air_date': '2000-05-22 01:00:00'},
  {'season': 8,
   'episode': 1,
   'name': 'Within (1)',
   'air_date': '2000-11-06 02:00:00'},
  {'season': 8,
   'episode': 2,
   'name': 'Without (2)',
   'air_date': '2000-11-13 02:00:00'},
  {'season': 8,
   'episode': 3,
   'name': 'Patience',
   'air_date': '2000-11-20 02:00:00'},
  {'season': 8,
   'episode': 4,
   'name': 'Roadrunners',
   'air_date': '2000-11-27 02:00:00'},
  {'season': 8,
   'episode': 5,
   'name': 'Invocation',
   'air_date': '2000-12-04 02:00:00'},
  {'season': 8,
   'episode': 6,
   'name': 'Redrum',
   'air_date': '2000-12-11 02:00:00'},
  {'season': 8,
   'episode': 7,
   'name': 'Via Negativa',
   'air_date': '2000-12-18 02:00:00'},
  {'season': 8,
   'episode': 8,
   'name': 'Surekill',
   'air_date': '2001-01-08 02:00:00'},
  {'season': 8,
   'episode': 9,
   'name': 'Salvage',
   'air_date': '2001-01-15 02:00:00'},
  {'season': 8,
   'episode': 10,
   'name': 'Badlaa',
   'air_date': '2001-01-22 02:00:00'},
  {'season': 8,
   'episode': 11,
   'name': 'The Gift',
   'air_date': '2001-02-05 02:00:00'},
  {'season': 8,
   'episode': 12,
   'name': 'Medusa',
   'air_date': '2001-02-12 02:00:00'},
  {'season': 8,
   'episode': 13,
   'name': 'Per Manum',
   'air_date': '2001-02-19 02:00:00'},
  {'season': 8,
   'episode': 14,
   'name': 'This is Not Happening (1)',
   'air_date': '2001-02-26 02:00:00'},
  {'season': 8,
   'episode': 15,
   'name': 'DeadAlive (2)',
   'air_date': '2001-04-02 01:00:00'},
  {'season': 8,
   'episode': 16,
   'name': 'Three Words',
   'air_date': '2001-04-09 01:00:00'},
  {'season': 8,
   'episode': 17,
   'name': 'Empedocles',
   'air_date': '2001-04-16 01:00:00'},
  {'season': 8,
   'episode': 18,
   'name': 'Vienen',
   'air_date': '2001-04-23 01:00:00'},
  {'season': 8,
   'episode': 19,
   'name': 'Alone',
   'air_date': '2001-05-07 01:00:00'},
  {'season': 8,
   'episode': 20,
   'name': 'Essence (1)',
   'air_date': '2001-05-14 01:00:00'},
  {'season': 8,
   'episode': 21,
   'name': 'Existence (2)',
   'air_date': '2001-05-21 01:00:00'},
  {'season': 9,
   'episode': 1,
   'name': 'Nothing Important Happened Today (1)',
   'air_date': '2001-11-12 02:00:00'},
  {'season': 9,
   'episode': 2,
   'name': 'Nothing Important Happened Today (2)',
   'air_date': '2001-11-19 02:00:00'},
  {'season': 9,
   'episode': 3,
   'name': 'Dæmonicus',
   'air_date': '2001-12-03 02:00:00'},
  {'season': 9,
   'episode': 4,
   'name': '4-D',
   'air_date': '2001-12-10 02:00:00'},
  {'season': 9,
   'episode': 5,
   'name': 'Lord of the Flies',
   'air_date': '2001-12-17 02:00:00'},
  {'season': 9,
   'episode': 6,
   'name': 'Trust No 1',
   'air_date': '2002-01-07 02:00:00'},
  {'season': 9,
   'episode': 7,
   'name': 'John Doe',
   'air_date': '2002-01-14 02:00:00'},
  {'season': 9,
   'episode': 8,
   'name': 'Hellbound',
   'air_date': '2002-01-28 02:00:00'},
  {'season': 9,
   'episode': 9,
   'name': 'Provenance (1)',
   'air_date': '2002-03-04 02:00:00'},
  {'season': 9,
   'episode': 10,
   'name': 'Providence (2)',
   'air_date': '2002-03-11 02:00:00'},
  {'season': 9,
   'episode': 11,
   'name': 'Audrey Pauley',
   'air_date': '2002-03-18 02:00:00'},
  {'season': 9,
   'episode': 12,
   'name': 'Underneath',
   'air_date': '2002-04-01 02:00:00'},
  {'season': 9,
   'episode': 13,
   'name': 'Improbable',
   'air_date': '2002-04-08 01:00:00'},
  {'season': 9,
   'episode': 14,
   'name': 'Scary Monsters',
   'air_date': '2002-04-15 01:00:00'},
  {'season': 9,
   'episode': 15,
   'name': 'Jump the Shark',
   'air_date': '2002-04-22 01:00:00'},
  {'season': 9,
   'episode': 16,
   'name': 'William',
   'air_date': '2002-04-29 01:00:00'},
  {'season': 9,
   'episode': 17,
   'name': 'Release',
   'air_date': '2002-05-06 01:00:00'},
  {'season': 9,
   'episode': 18,
   'name': 'Sunshine Days',
   'air_date': '2002-05-13 01:00:00'},
  {'season': 9,
   'episode': 19,
   'name': 'The Truth (1)',
   'air_date': '2002-05-20 01:00:00'},
  {'season': 9,
   'episode': 20,
   'name': 'The Truth (2)',

In [20]:
# 1
serials = pd.json_normalize(data=df_json['shows'], meta=['show', 'runtime', 'network'], record_path='episodes')
serials

,season,episode,name,air_date,show,runtime,network
0,1,1,Pilot,1993-09-11 01:00:00,The X-Files,60,FOX
1,1,2,Deep Throat,1993-09-18 01:00:00,The X-Files,60,FOX
2,1,3,Squeeze,1993-09-25 01:00:00,The X-Files,60,FOX
3,1,4,Conduit,1993-10-02 01:00:00,The X-Files,60,FOX
4,1,5,The Jersey Devil,1993-10-09 01:00:00,The X-Files,60,FOX
...,...,...,...,...,...,...,...
477,7,18,Dirty Girls,2003-04-16 00:00:00,Buffy the Vampire Slayer,60,UPN
478,7,19,Empty Places,2003-04-30 00:00:00,Buffy the Vampire Slayer,60,UPN
479,7,20,Touched,2003-05-07 00:00:00,Buffy the Vampire Slayer,60,UPN
480,7,21,End of Days,2003-05-14 00:00:00,Buffy the Vampire Slayer,60,UPN
481,7,22,Chosen,2003-05-21 00:00:00,Buffy the Vampire Slayer,60,UPN

In [23]:
# 2
lst = []
for s in serials['show'].unique():
    lst.append(serials[serials['show'] == s])

In [24]:
lst

[     season  episode                   name             air_date         show  \
 0         1        1                  Pilot  1993-09-11 01:00:00  The X-Files
 1         1        2            Deep Throat  1993-09-18 01:00:00  The X-Files
 2         1        3                Squeeze  1993-09-25 01:00:00  The X-Files
 3         1        4                Conduit  1993-10-02 01:00:00  The X-Files
 4         1        5       The Jersey Devil  1993-10-09 01:00:00  The X-Files
 ..      ...      ...                    ...                  ...          ...
 213      11        6                 Kitten  2018-02-08 01:00:00  The X-Files
 214      11        7           Rm9sbG93ZXJz  2018-03-01 01:00:00  The X-Files
 215      11        8               Familiar  2018-03-08 01:00:00  The X-Files
 216      11        9  Nothing Lasts Forever  2018-03-15 00:00:00  The X-Files
 217      11       10         My Struggle IV  2018-03-22 00:00:00  The X-Files

     runtime network
 0        60     FOX
 1        60     FOX
 2        60     FOX
 3        60     FOX
 4        60     FOX
 ..      ...     ...
 213      60     FOX
 214      60     FOX
 215      60     FOX
 216      60     FOX
 217      60     FOX

 [218 rows x 7 columns],
      season  episode                name             air_date  show runtime  \
 218       1        1           Pilot (1)  2004-09-23 00:00:00  Lost      60
 219       1        2           Pilot (2)  2004-09-30 00:00:00  Lost      60
 220       1        3         Tabula Rasa  2004-10-07 00:00:00  Lost      60
 221       1        4           Walkabout  2004-10-14 00:00:00  Lost      60
 222       1        5        White Rabbit  2004-10-21 00:00:00  Lost      60
 ..      ...      ...                 ...                  ...   ...     ...
 334       6       14       The Candidate  2010-05-05 01:00:00  Lost      60
 335       6       15      Across the Sea  2010-05-12 01:00:00  Lost      60
 336       6       16  What They Died For  2010-05-19 01:00:00  Lost      60
 337       6       17         The End (1)  2010-05-24 01:00:00  Lost      60
 338       6       18         The End (2)  2010-05-24 01:00:00  Lost      60

     network
 218     ABC
 219     ABC
 220     ABC
 221     ABC
 222     ABC
 ..      ...
 334     ABC
 335     ABC
 336     ABC
 337     ABC
 338     ABC

 [121 rows x 7 columns],
      season  episode                                name             air_date  \
 339       1        1            Welcome to the Hellmouth  1997-03-11 01:00:00
 340       1        2                         The Harvest  1997-03-11 01:00:00
 341       1        3                               Witch  1997-03-18 01:00:00
 342       1        4                       Teacher's Pet  1997-03-26 01:00:00
 343       1        5  Never Kill a Boy on the First Date  1997-04-01 01:00:00
 ..      ...      ...                                 ...                  ...
 477       7       18                         Dirty Girls  2003-04-16 00:00:00
 478       7       19                        Empty Places  2003-04-30 00:00:00
 479       7       20                             Touched  2003-05-07 00:00:00
 480       7       21                         End of Days  2003-05-14 00:00:00
 481       7       22                              Chosen  2003-05-21 00:00:00

                          show runtime network
 339  Buffy the Vampire Slayer      60     UPN
 340  Buffy the Vampire Slayer      60     UPN
 341  Buffy the Vampire Slayer      60     UPN
 342  Buffy the Vampire Slayer      60     UPN
 343  Buffy the Vampire Slayer      60     UPN
 ..                        ...     ...     ...
 477  Buffy the Vampire Slayer      60     UPN
 478  Buffy the Vampire Slayer      60     UPN
 479  Buffy the Vampire Slayer      60     UPN
 480  Buffy the Vampire Slayer      60     UPN
 481  Buffy the Vampire Slayer      60     UPN

 [143 rows x 7 columns]]

In [25]:
len(lst)

3

In [26]:
excel_file = pd.ExcelWriter('My_Serials.xlsx')
excel_file

In [27]:
for df in lst:
    name = df['show'].unique()[0]
    df.to_excel(excel_writer=excel_file, sheet_name=name, index=False)

In [29]:
excel_file.close()